### ISSUE TITLE
建议：添加到brew cask 源

### ISSUE THREAD

**Issue by fashioncj** [Ji4n1ng/OpenInTerminal#1]

**Comment by Ji4n1ng** [comment]
好的

**Comment by fashioncj** [comment]
@Ji4n1ng 如果像我这样用f.lux这样自动切换light/dark的就有点不方便 。
看看能不能搞成系统API支持

**Comment by Ji4n1ng** [comment]
目前，打开 Terminal 和 iTerm 都是单独的应用，后面还会支持 Hyper。所以我想等合并成一个版本之后，再上传到 brew cask。

自动切换图标这个功能，可能需要让应用一直处于运行状态。目前是打开终端之后就退出了，不会常驻后台。所以还需要找一找优雅的解决办法。

**Comment by fashioncj** [comment]
应用打开的时候可以获取当前的主题，然后进行替换~
虽然不优雅还是能用~毕竟自动换肤的人会有一个产品预期。

合并的事情，是不是考虑加一个配置项就好，我看代码只是call就改一下

**Comment by UniqueSimon** [comment]
https://gist.github.com/UniqueSimon/27fe7a0745c92af80bf690e63153a3c6
https://gist.github.com/UniqueSimon/e5e4283f4fa60eb30a04887c5e980e21
https://gist.github.com/UniqueSimon/463a2a15e0aa450048f261a4f68268e5
@Ji4n1ng 你好，cask我建好了，但是合并需要运行brew cask style检查，需要升级ruby才行，我不知道macos怎么升级ruby，还是麻烦你pull吧，哈哈

**Comment by Ji4n1ng** [comment]
@UniqueSimon 非常感谢。同时支持 Terminal、iTerm2 和 Hyper 的合一版本，目前正在开发。等更新完之后，我会用你的 gist 上传至 brew cask 的。😀

**Comment by YiYiZheng** [comment]
现在使用 Terminal 版本的，会弹出两个终端框。

**Comment by Ji4n1ng** [comment]
@YiYiZheng 这一般是发生在第一次打开 Terminal 的时候。平常可以使用 `Cmd + W` 来关闭 Terminal 窗口。不退出 Terminal 就好了。这个问题我查过了，目前还没有想到好的解决办法。后面如果有解决办法，我会及时更新的。谢谢支持 😃

**Comment by Ji4n1ng** [comment]
终于审核通过了。现在可以通过 `brew cask install openinterminal` 来安装了，当前的版本是 v0.2.0

**Comment by Ji4n1ng** [comment]
@fashioncj 这个图标动态替换，目前还没有找到好的解决办法。目前正在开发的是，通过加一个 FinderSync Extension 到 Toolbar 上，但是也需要 Force Quit 强制退出 Finder，再打开 Finder，才能刷新 icon。不知道今年 WWDC 上 10.15 会不会提供新的 API。图标问题可以新建一个 issue 再讨论。不过这个不是核心功能，也就不是很急去实现。

**Comment by Ji4n1ng** [comment]
@fashioncj 刚 Release 的 v0.9.0 支持 Dark Mode 了。目前的版本是以 Finder 扩展的形式。
