### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by idejie** [Ji4n1ng/OpenInTerminal#10]
:shipit: I think some shortcuts maybe work better and more efficiently, like a combination of <kbd>⌘ </kbd> \ <kbd>⌥</kbd>  and other.

**Comment by Ji4n1ng** [comment]
Good advice! The new version will consider this feature. Thank you for your kind advice. 😃

**Comment by idejie** [comment]
**Old Wang , So Strong .**
老王太强了！

**Comment by Ji4n1ng** [comment]
😂哈哈哈哈哈。老杨说笑了，谢谢来支持。没想到这么多人点赞这个项目，我会尽可能地让这个项目变得更棒。😀

**Comment by idejie** [comment]
等一个`Pro`版

**Comment by Ji4n1ng** [comment]
好的，没问题

**Comment by Camji55** [comment]
@idejie In the meantime while this is being looked into, you can try this: https://appleinsider.com/articles/18/03/14/how-to-create-keyboard-shortcuts-to-launch-apps-in-macos-using-automator

**Comment by idejie** [comment]
@Camji55 Got it and thanks a lot.

**Comment by Ji4n1ng** [comment]
@idejie v0.10.0 已支持键盘快捷键

链接：https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.10.0
