### ISSUE TITLE
Add 'Noto' as a supported text editor

### ISSUE THREAD

**Issue by thebitstick** [Ji4n1ng/OpenInTerminal#102]
## Summarize this feature
Add 'Noto' as a supported text editor
## Why should this feature be included?
Simple text editor I prefer to use.
## Additional information
https://github.com/brunophilipe/Noto

**Comment by Ji4n1ng** [comment]
You can use OpenInTerminal v2.3.0 or OpenInTerminal-Lite v1.2.0. Both of them support custom app. You can use the following command to check if Noto is supported by OpenInTerminal.

```
open -a Noto ~/Desktop
```
