### ISSUE TITLE
Open in Terminal from Finder

### ISSUE THREAD

**Issue by deko96** [Ji4n1ng/OpenInTerminal#104]
## What is the issue?
When you have terminal already opened and you press on the "Open in Terminal" action through the Finder app, it just focuses the terminal but it doesn't change the directory.
If there's no terminal window opened, the feature works as expected.

## How does one reproduce the issue?
1. Open terminal
2. Open finder
3. Navigate to a folder where you'd like to open terminal
4. Click on the "Open In Terminal" button and then select "Open in terminal" option.
**OR** 
Right click inside the folder and then select "Open in terminal"

## Debug information (Logs, OS, Hardware, Version, etc.)
![Screen Shot 2020-07-29 at 20 05 14](https://user-images.githubusercontent.com/11915426/88836356-d5e54380-d1d6-11ea-95a7-047b02bc5db7.png)

FYI this isn't something that was caused by the latest update, it existed in **2.2.1** as well.

**Comment by Ji4n1ng** [comment]
Did you set it to open a new tab of Terminal? This feature cannot work now. You could try to use open a new window of Terminal. Opening a new tab only works on iTerm now.
