### ISSUE TITLE
Finder拓展暂时卡死无效

### ISSUE THREAD

**Issue by hsingll** [Ji4n1ng/OpenInTerminal#107]
## What is the issue?

Finder拓展打开终端模拟器和VSCode卡死，仅复制路径有效。
卡死时，屏幕、鼠标、键盘完全无响应。约半分钟到一分钟后可以响应，此时状态栏会出现齿轮按钮，显示正在运行相应的脚本(位于~/资源库/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension/)，但是此时不能打卡任何应用或打字，否则又将卡死数秒。
直到状态栏齿轮图标消失，可以正常使用电脑，但是打开终端模拟器和VSCode仍然没有执行。

另外，直接运行~/资源库/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension/下的脚本可以正常打开终端模拟器和VSCode，包括选中文件时。

## How does one reproduce the issue?

选中文件，使用Finder上下文菜单或者工具栏菜单选择打开iTerm或打开VSCode。

## Screenshots

无截图。

## Debug information (Logs, OS, Hardware, Version, etc.)

[OpenInTerminal-0.log](https://github.com/Ji4n1ng/OpenInTerminal/files/5179954/OpenInTerminal-0.log)
macOS 10.14.6,MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports),OpenInTerminal 2.2.1/2.2.2

**Comment by Ji4n1ng** [comment]
按住Option，右击访达，选择重启访达即可。如果还不行，重启电脑。

**Comment by hsingll** [comment]
> 按住Option，右击访达，选择重启访达即可。如果还不行，重启电脑。

你好，刚才尝试了重启访达和重启电脑，但是仍会卡住。

**Comment by Ji4n1ng** [comment]
@hsingll 以前我也碰到过，但是不会卡这么久，一般是齿轮运行几秒完没有效果，一般通过重启访达就好了。现在你的问题暂时不知道是什么原因。建议先不用OpenInTerminal了，尝试一下OpenInTerminal-Lite和OpenInEditor-Lite。如果这两个软件还存在卡死的问题，那也没办法了。

**Comment by hsingll** [comment]
> @hsingll 以前我也碰到过，但是不会卡这么久，一般是齿轮运行几秒完没有效果，一般通过重启访达就好了。现在你的问题暂时不知道是什么原因。建议先不用OpenInTerminal了，尝试一下OpenInTerminal-Lite和OpenInEditor-Lite。如果这两个软件还存在卡死的问题，那也没办法了。

好的，谢谢
