### ISSUE TITLE
Feature request: Open in new tab

### ISSUE THREAD

**Issue by ralcr** [Ji4n1ng/OpenInTerminal#11]
Hi, is it possible to open a new tab into an existing Terminal instead a new Terminal?

**Comment by Camji55** [comment]
I know that Hyper has a plugin to do this automatically, not sure about the others though. When I get some free time, I’ll take a look into the feasibility of this.

**Comment by Camji55** [comment]
@Ji4n1ng This issue may be closed and be tracked within https://github.com/Ji4n1ng/OpenInTerminal/issues/16

**Comment by Ji4n1ng** [comment]
@ralcr v0.4.0 has provided this feature. You can download from
https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.4.0

The usage is in the following link. You can see it in `README`. 😀
https://github.com/Ji4n1ng/OpenInTerminal#4-open-in-a-new-tab-or-window

**Comment by catch22** [comment]
This features no longer works for me in the latest version 2.0.1 (using the default Terminal app).

**Comment by Ji4n1ng** [comment]
Hi @catch22 Opening in a new tab needs permissions in `Accessibility`. You can find it in `Security & Privacy` -> `Accessbility` -> `Privacy`

<img width="668" alt="Screen Shot 2019-07-25 at 9 10 21 PM" src="https://user-images.githubusercontent.com/11001224/61877035-ccb8fb00-af20-11e9-86f8-e9926e71247d.png">

**Comment by catch22** [comment]
Strangely this is enabled for me (it only started failing when updating to 2.x). Let me try to disable and enable again.

**Comment by catch22** [comment]
Ha, this worked. Thank you!

**Comment by Ji4n1ng** [comment]
@catch22 You're welcome!
