### ISSUE TITLE
OpenInEditor-lite opens Desktop folder instead of the current folder when nothing selected in Finder

### ISSUE THREAD

**Issue by andreiborisov** [Ji4n1ng/OpenInTerminal#110]
## What is the issue?
OpenInEditor-lite opens Desktop folder instead of the current folder when nothing selected in Finder. It appears to be a regression in v1.1.4.

## How does one reproduce the issue?

Navigate to a folder, use OpenInEditor-lite

## Debug information (Logs, OS, Hardware, Version, etc.)

macOS 10.15.7
OpenInEditor-lite v1.1.4

**Comment by Ji4n1ng** [comment]
This bug has been fixed in v1.1.5. Please let me know if you have any questions.

**Comment by andreiborisov** [comment]
I can confirm it works beautifully now🙌
