### ISSUE TITLE
icons.zip does not include the icon of icon_terminal_dark

### ISSUE THREAD

**Issue by xiaodang** [Ji4n1ng/OpenInTerminal#112]
## What is the issue?
![image](https://user-images.githubusercontent.com/7018239/96995678-2283b500-1561-11eb-80f2-dbb74746d91a.png)

## How does one reproduce the issue?
release version: OpenInTerminal-Lite v1.1.5

**Comment by PetrusM** [comment]
While the problem is not resolved, you can still download the icons of the 1.1.0 release [here](https://github.com/Ji4n1ng/OpenInTerminal/releases/download/1.1.0/icons.zip), they contain no known bug 😆
