### ISSUE TITLE
请求打开终端里新增Electerm终端的支持

### ISSUE THREAD

**Issue by gufyapk** [Ji4n1ng/OpenInTerminal#113]
## Summarize this feature
希望在打开终端里新增Electerm终端的支持或可自定义终端，而不是必须使用指定的终端.
## Why should this feature be included?
这是一个开源的好用的集成终端平台，支持多端，现在使用的人数越来越多，请考虑增加支持.

**Comment by Ji4n1ng** [comment]
坏消息是经过测试，该应用不被支持。如何判断你的应用是否被 OpenInTerminal 支持：

```
open -a Electerm ~/Desktop
```

这条命令如果仅仅只是打开了应用，而没有让应用打开到桌面，那么该应用就不受支持。
