### ISSUE TITLE
Conflict with OneDrive Finder Extension

### ISSUE THREAD

**Issue by Bridgee** [Ji4n1ng/OpenInTerminal#116]
## What is the issue?
Conflict with OneDrive Finder Extension
## How does one reproduce the issue?
OneDrive Sync icon would disappear in Finder randomly. It can be fixed by disabling and enabling the Extensions (both OpenInTerminal and OneDrive) in Preference, but it would come back shortly.

**Comment by advicepyro** [comment]
Also getting this issue. If you turn off OpenInTerminal in Finder Extensions the OneDrive icons come back. But in doing so OpenInTerminal's toolbar button disappears until the next Finder start.

**Comment by emanuelst** [comment]
I have a similar issue with external disk icons. This might also be a macOS bug, as it appears with several finder extensions: https://www.reddit.com/r/MacOS/comments/jup0eb/wrong_external_disks_icons_in_finders_sidebar/

**Comment by moriwang** [comment]
I recorded a video for that.


https://user-images.githubusercontent.com/9151525/112015481-d1efa280-8b66-11eb-93a2-e38041d1062a.mov

**Comment by Ji4n1ng** [comment]
It seems like Apple has fixed this bug. I just noticed that there is no such bug in Big Sur 11.5.2. I haven't used Mac as my main machine for more than half a year, so I don't know which version fixs this. Anyway, glad to see that.
