### ISSUE TITLE
Not working in macOS 11

### ISSUE THREAD

**Issue by moriwang** [Ji4n1ng/OpenInTerminal#117]
## What is the issue?

Open in terminal and Open in Editor not shown in Finder Toolbar Menu and Finder Context menu.

<img width="196" alt="截屏2020-11-13 下午6 25 09" src="https://user-images.githubusercontent.com/9151525/99062220-9a338580-25dd-11eb-9f59-d1029180985b.png">
<img width="148" alt="截屏2020-11-13 下午6 26 13" src="https://user-images.githubusercontent.com/9151525/99062276-b7685400-25dd-11eb-8c4b-3b0c6bb537f4.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS 11.0.1
OpenInTerminal 2.2.3

**Comment by moriwang** [comment]
找到了一个修复的方式。目测 BUG 是 「应用到访达上下文菜单」导致的。
1. 全选
<img width="423" alt="截屏2020-11-13 下午9 46 48" src="https://user-images.githubusercontent.com/9151525/99078668-bd6c2e00-25f9-11eb-9053-adbee16e2a63.png">
2. 取消选择「应用到访达上下文菜单」。
<img width="426" alt="截屏2020-11-13 下午9 48 23" src="https://user-images.githubusercontent.com/9151525/99078813-f5737100-25f9-11eb-9978-fc299235964a.png">
3. 全部取消也可以保留住。
<img width="449" alt="截屏2020-11-13 下午9 49 18" src="https://user-images.githubusercontent.com/9151525/99078881-163bc680-25fa-11eb-9674-6299f1a07283.png">
4. 如果勾选 「应用到访达上下文菜单」就不行了，需要重复 1-3 步修复。
<img width="467" alt="截屏2020-11-13 下午9 49 59" src="https://user-images.githubusercontent.com/9151525/99078944-2e134a80-25fa-11eb-8a0e-932cfc913f14.png">

**Comment by Ji4n1ng** [comment]
感谢提交issue。因为我还没有升级新系统，这个bug可能需要一段时间去修复。

**Comment by Ji4n1ng** [comment]
@moriwang 你可以更新最新版本了 v2.3.0，这个版本我测试着没有问题
