### ISSUE TITLE
Big Sur toolbar icons

### ISSUE THREAD

**Issue by luckman212** [Ji4n1ng/OpenInTerminal#118]
Anyone got some good toolbar icons that match the UI appearance of macOS 11 Big Sur?

**Comment by fharper** [comment]
That would be awesome!

**Comment by Ji4n1ng** [comment]
I'm working on it and new icons will be released with next version.

**Comment by Ji4n1ng** [comment]
Since it will take a while before the new version is released, I put the new icon here in advance. Hope you like them. Any suggestions are welcome.

[Icons for Big Sur.zip](https://github.com/Ji4n1ng/OpenInTerminal/files/5746137/Icons.for.Big.Sur.zip)

**Comment by andreiborisov** [comment]
Beautiful, thank you!

**Comment by fharper** [comment]
Thanks!
