### ISSUE TITLE
OpenInTerminal-Lite v1.1.5/ Big Sur / Can't remember iTerm2 position

### ISSUE THREAD

**Issue by sh2sg** [Ji4n1ng/OpenInTerminal#119]
It always opens iTerm2 at a fixed position regardless of the position of last closed iTerm2 window.

**Comment by Ji4n1ng** [comment]
OpenInTerminal and OpenInTerminal-Lite are only responsible for opening applications. It's not a bug of OpenInTerminal-Lite. 😂
