### ISSUE TITLE
Open in new window for iTerm

### ISSUE THREAD

**Issue by ravernkoh** [Ji4n1ng/OpenInTerminal#12]
Is it possible to configure this to open a new window in iTerm instead of opening a new tab in an existing session?

**Comment by Camji55** [comment]
Please refer to the previous issue. This has already been brought up. Thanks you!

**Comment by ravernkoh** [comment]
Are you referring to #11? That issue is a request to open a new tab, instead of a new window, in the macOS Terminal. This issue is a request to open a new window, instead of a new tab, in iTerm. It's quite the opposite 😅

**Comment by Camji55** [comment]
My apologies! Will look into this as well.

**Comment by ravernkoh** [comment]
Thanks 😁

**Comment by Camji55** [comment]
@ravernkoh This can definitely be done. In an upcoming release, there will be a preference pane where you'll be able to set whether it prefers new tabs or windows.

**Comment by Camji55** [comment]
@Ji4n1ng This issue may be closed and be tracked within https://github.com/Ji4n1ng/OpenInTerminal/issues/16
