### ISSUE TITLE
Please add Textastic to the list of supported editors

### ISSUE THREAD

**Issue by KenCrandall** [Ji4n1ng/OpenInTerminal#122]
## Summarize this feature

Please add [Textastic](https://www.textasticapp.com/mac.html) to the list of supported editors

## Why should this feature be included?

This is my preferred editor and it is simple and lightweight.

## Additional information

Website is here: [https://www.textasticapp.com/mac.html](https://www.textasticapp.com/mac.html)

**Comment by Ji4n1ng** [comment]
OpenInTerminal v2.3.0 and OpenInEditor v1.2.0 have released. They all support adding a custom app. Please see the README.

You could run the following command to test whether Textastic is supported.

```
open -a Textastic ~/Desktop
```
