### ISSUE TITLE
无法识别 iterm on Apple Silicon M1

### ISSUE THREAD

**Issue by cikichen** [Ji4n1ng/OpenInTerminal#125]
## What is the issue?
iterm2 not recognized on Apple Silicon M1

## Screenshots
![image](https://user-images.githubusercontent.com/1478821/103882146-590bad80-5116-11eb-9f60-5a937f2449f7.png)

![image](https://user-images.githubusercontent.com/1478821/103882515-e18a4e00-5116-11eb-97bb-3fc5aaa4568b.png)

## Debug information (Logs, OS, Hardware, Version, etc.)
macbook pro m1 big sur 11.1

**Comment by Ji4n1ng** [comment]
能告诉我你的 iTerm 的安装路径吗。可能这个路径被我忽略了，到底无法识别。

**Comment by cikichen** [comment]
> 能告诉我你的 iTerm 的安装路径吗。可能这个路径被我忽略了，导致无法识别。另外，最新版本的应用可以强制添加受支持的应用，版本是 v2.3.0。
> 
> 因为我没有 M1 的 Mac，我一直没有测试在新机器上有没有 bug。所以如果你在使用过程中有什么异常，非常欢迎来提问题 😀

就是application下面

**Comment by scoolor** [comment]
macos big sur 11.2.3 apple m1  版本访达菜单里没有显示快捷图标 还是有些小问题。

**Comment by Ji4n1ng** [comment]
@cikichen 现在还有这个问题吗

**Comment by cikichen** [comment]
> @cikichen 现在还有这个问题吗
后面一直用lite了，不知道还有没有
