### ISSUE TITLE
Update icons asset

### ISSUE THREAD

**Issue by MatteoCarnelos** [Ji4n1ng/OpenInTerminal#127]
This update is requested by #126 in order to correctly switch between some "non-Big Sur" icons.

The current `Icons.zip` file in the release page contains inconsistent file names, in particular, some finish with `_light.icns` and others with `_white.icns`. This may break the correct behavior of the automatic icon switching for those not using Big Sur icons.

To fix this issue the following naming convention should be adopted for all the file names:
```
icon_<type>_<dark/light>.icns
```
So the following changes are needed:
* Rename `icon_hyper_white.icns` to `icon_hyper_light.icns`
* Rename `icon_iterm_white.icns` to `icon_iterm_light.icns`

Moreover, it would be also useful to add generic icons to the pack (as it's done for Big Sur icons), like: `icon_editor_light.icns`, `icon_editor_dark.icns`, `icon_terminal_light.icns` and `icon_terminal_dark.icns`, for those who are not using the proposed ones.

**Comment by Ji4n1ng** [comment]
Hi, @MatteoCarnelos I have fixed this issue and the icons are [here](https://github.com/Ji4n1ng/OpenInTerminal/releases/download/v1.2.0/Icons.zip). Please let me know if the icons need to be modified.

**Comment by MatteoCarnelos** [comment]
They are perfect now! Thank you!
