### ISSUE TITLE
Conflict with Google Drive's Finder Extension

### ISSUE THREAD

**Issue by advicepyro** [Ji4n1ng/OpenInTerminal#129]
## What is the issue?
Identical issue to #116, but applies to Google Drive. When OpenInTerminal's Finder Extension is active, the status icons for files in my Google Drive in the Finder do not show up.

## How does one reproduce the issue?
Enable both extensions for OpenInTerminal and Google Drive, then restart Finder or macOS.

I can observe this by seeing OpenInTerminal's toolbar button active on the toolbar, but files in my Google Drive don't have icons. If I disable OpenInTerminal's extension, the icons are restored.

**Comment by emanuelst** [comment]
I have a similar issue with external disk icons. This might also be a macOS bug, as it appears with several finder extensions: https://www.reddit.com/r/MacOS/comments/jup0eb/wrong_external_disks_icons_in_finders_sidebar/

**Comment by Ji4n1ng** [comment]
It seems like Apple has fixed this bug. I just noticed that there is no such bug in Big Sur 11.5.2. I haven't used Mac as my main machine for more than half a year, so I don't know which version fixs this. Anyway, glad to see that.
