### ISSUE TITLE
Folders with "(" or ")" characters do not open

### ISSUE THREAD

**Issue by Porco-Rosso** [Ji4n1ng/OpenInTerminal#13]
When set to open in Hyper, I cannot seem to open folders that contain parentheses.
I see the app try to launch but fail.

**Comment by Camji55** [comment]
Interesting 🧐 Nobody likes an app that crashes! I’ll look into a fix for this. Thank you for bringing this up.

**Comment by Camji55** [comment]
@Porco-Rosso Issue will be resolved with the merge of https://github.com/Ji4n1ng/OpenInTerminal/pull/14

**Comment by Camji55** [comment]
@Ji4n1ng This issue can be closed.

**Comment by Ji4n1ng** [comment]
@Porco-Rosso v0.3.0 has fixed this bug. You can download from
https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.3.0

As far as I can tell, Terminal supports all special characters. However iTerm and Hyper do not support backslash `\` and double quotes `"` in the path. So please avoid these two special characters as much as possible. You can see the **FAQ** in README. 😀
