### ISSUE TITLE
能否在偏好设置中添加一个退出按钮？

### ISSUE THREAD

**Issue by moriwang** [Ji4n1ng/OpenInTerminal#131]
## Why should this feature be included?
如果设置隐藏状态栏图标，想要退出 App，就只能先取消勾选隐藏状态栏图标，再点退出。

**Comment by Ji4n1ng** [comment]
可以，会在下个版本加上

**Comment by Ji4n1ng** [comment]
版本 v2.3.1 已加上该功能，在偏好设置->高级中
