### ISSUE TITLE
[OpenInTerminal-Lite] Last update does not work with Alacritty 

### ISSUE THREAD

**Issue by superlevure** [Ji4n1ng/OpenInTerminal#132]
## What is the issue?
Since last update, trying to open a folder in terminal with OpenInTerminal-Lite and Alacritty results in: 

`[2021-01-19 21:08:22.235140000] [ERROR] [alacritty] Invalid working directory: "file:///Volumes/some/folder"`

I used the following command to set Alacritty by default:
`defaults write wang.jianing.app.OpenInTerminal-Lite LiteDefaultTerminal Alacritty`

## How does one reproduce the issue?

Open any folder

## Debug information (Logs, OS, Hardware, Version, etc.)
alacritty 0.7.1 (a852eb8)
openinterminal-lite: 1.2.0

**Comment by Ji4n1ng** [comment]
This bug will be fixed soon.

**Comment by Ji4n1ng** [comment]
The new version v1.2.1 has fixed this bug.
