### ISSUE TITLE
OpenInEdit-Lite can't save the default app as sublime

### ISSUE THREAD

**Issue by zszhere** [Ji4n1ng/OpenInTerminal#134]
## What is the issue?
OpenInEdit-Lite can't save the default app
OpenInEdit-Lite 无法保存默认设置为sublime， 每次打开都需要重新选择

## How does one reproduce the issue?
just click OpenInEdit-Lite in finder, you will be asked to select app every time
第一次在finder中打开OpenInEdit-Lite时，选择sublime，后面每次打开都提示选择默认app

## Screenshots
no
无

## Debug information (Logs, OS, Hardware, Version, etc.)
mbp13 2020 with intel cpu，BigSur 11.1

## something maybe help
I solved this after run:
```
defaults write wang.jianing.app.OpenInEditor-Lite LiteDefaultEditor Sublime\ Text
```

**Comment by Ji4n1ng** [comment]
这个bug会尽快修复

**Comment by Ji4n1ng** [comment]
该 bug 已在 v1.2.1 修复
