### ISSUE TITLE
Alacritty is not working as expected

### ISSUE THREAD

**Issue by tobx** [Ji4n1ng/OpenInTerminal#135]
## What is the issue?
Cannot set Alacritty as Terminal app to use with OpenInTerminal-Lite.

## How does one reproduce the issue?
`Terminal` was set. Now I want to set Alacritty by entering the following in the shell as documented:
```bash
defaults write wang.jianing.app.OpenInTerminal-Lite LiteDefaultTerminal Alacritty
```

Furthermore I tried to remove the old setting first:
```bash
defaults remove wang.jianing.app.OpenInTerminal-Lite LiteDefaultTerminal
defaults write wang.jianing.app.OpenInTerminal-Lite LiteDefaultTerminal Alacritty
```

Now it asks me which Terminal to choose, but Alacritty is not in the list. If I choose another Terminal app, this is used and I can start those steps again.

**Comment by Ji4n1ng** [comment]
Hi @tobx . Which version of OpenInTerminal-Lite are you using? This command only works for version 1.2.0 and above. If you are using old version, please update it.

**Comment by tobx** [comment]
Hi @Ji4n1ng, thank you, I was sure I checked the version, but `brew` showed me the available version and I thought it is the installed one. After an upgrade it works as expected.
