### ISSUE TITLE
OpenInTerminal-Lite does not open paths with whitespace in Alacritty

### ISSUE THREAD

**Issue by tobx** [Ji4n1ng/OpenInTerminal#136]
## What is the issue?
OpenInTerminal-Lite does not open paths with whitespace in Alacritty.

## How does one reproduce the issue?
- Install Alacritty
- Configure Alacritty to be used with OpenInTerminal-Lite
- Create a folder with spaces (e.g. `/Users/username/path with whitespace/`)
- Open folder with OpenInTerminal-Lite from Finder menu bar

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS 11.1
Alacritty 0.7.1
OpenInTerminal-Lite: 1.2.1

**Comment by Ji4n1ng** [comment]
This bug will be fixed as soon as possible.

**Comment by tborychowski** [comment]
Similar issue happens to me in the regular version (2.3.1) - when a path contains a space - "copy path" doesn't work, nor "Open in iTerm" (but Open in VSCode works).

**Comment by Ji4n1ng** [comment]
OpenInTerminal v2.3.2 and OpenInTerminal-Lite v1.2.2 have been released. Please let me know if there is any problem. 😀

**Comment by tborychowski** [comment]
Thanks @Ji4n1ng works perfectly now!

**Comment by tobx** [comment]
That was fast, thank you a lot @Ji4n1ng!
