### ISSUE TITLE
v.1.2.2 still doesn't support paths with spaces

### ISSUE THREAD

**Issue by jimtut** [Ji4n1ng/OpenInTerminal#139]
OpenInTerminal-Lite 1.2.2 doesn't support paths with spaces.  I went back to 1.2.1 and observed the same problem.  I went back to 1.2.0, and it works fine.  I thought at first it was a permission problem on an external drive, but I checked and it worked at the root level (/Volumes/Media), but not in sub-folders under that if there are spaces.

1.2.0 works fine, so I'll stick with that for now.

**Comment by wurzelsand** [comment]
In `App.swift` of `OpenInTerminalCore` line 69:

```swift
guard let url = URL(string: path) else {...}
```

Maybe meant:

```swift
let url = URL(fileURLWithPath: path)
```
???

**Comment by Ji4n1ng** [comment]
@wurzelsand Thanks for pointing out the bug. This will be fixed in the next version. Sorry for the problem.

**Comment by Ji4n1ng** [comment]
The new version has been released. Please let me know if there is any bug.

**Comment by jimtut** [comment]
Looks good, thanks!
