### ISSUE TITLE
Catalina全新安装，勾上应用到状态栏和上下文反而没生效

### ISSUE THREAD

**Issue by hsingll** [Ji4n1ng/OpenInTerminal#141]
## What is the issue?
Catalina全新安装，勾上应用到状态栏和上下文反而没生效，不勾反而Finder生效了。

## Screenshots
<img width="429" alt="Snipaste_2021-02-04_13-58-45" src="https://user-images.githubusercontent.com/26346635/106851525-61dda800-66f1-11eb-9956-dc52eb436b47.png">

**Comment by ch1dyc4t** [comment]
same on 10.15.7
