### ISSUE TITLE
OpenInTerminal-Lite 1.2.2 doesn't work if not in /Applications

### ISSUE THREAD

**Issue by indexofrefraction** [Ji4n1ng/OpenInTerminal#142]
I have all my small tools in /Applications/Tools/.../... 
to keep my /Applications reserved for main Applications

Sadly 1.2.2 doesn't work if it is not located in /Applications 
It would be really nice if you could fix that

**Comment by Ji4n1ng** [comment]
As shown in the gif below, it works fine on my mac.

![Kapture 2021-02-19 at 10 42 33](https://user-images.githubusercontent.com/11001224/108450037-739d7e80-729f-11eb-970e-e8eb753aa5f6.gif)

**Comment by indexofrefraction** [comment]
Hmm... ok, tx for checking ... and like this it works here, too...
but if the path is **/Applications/Tools/GUI and Dock/OpenInTerminal-Lite.app** it doesn't.
its probably the spaces ...

**Comment by Ji4n1ng** [comment]
I just tried what you said and it still works on my mac.
