### ISSUE TITLE
Only apply shortcuts on specific windows

### ISSUE THREAD

**Issue by devnoname120** [Ji4n1ng/OpenInTerminal#144]
## Summarize this feature

Only apply global shortcuts to specific windows (iterm, etc.)

## Why should this feature be included?

I've bound <kbd>Cmd + Shift + t</kbd> to `Open with default Terminal`. This works great but when I'm on Chrome the shortcut <kbd>Cmd + Shift + t</kbd> that opens the last closed tab doesn't work anymore.

## Additional information

Thank you for this great piece of software!

**Comment by Ji4n1ng** [comment]
Hi @devnoname120 . This shortcut key conflicts on these two apps. `Cmd + Shift + T` is a very useful shortcut on Chrome. I suggest you consider using `Cmd + Option + T` or `Cmd + Ctrl + T` to open terminal.

**Comment by devnoname120** [comment]
Thank you! I've switched my shortcut to this and it indeed doesn't seem to conflict with other shortcuts. 👌 
I wonder if the shortcut could be contextual (only apply if a specific window is open).

**Comment by Ji4n1ng** [comment]
Currently we cannot do that unless macOS gives the related API.
