### ISSUE TITLE
OpenInTerminal 2.3.2 does not open Paths with spaces in Terminal using keyboard shortcuts

### ISSUE THREAD

**Issue by ioemilio** [Ji4n1ng/OpenInTerminal#145]
## What is the issue?
OpenInTerminal 2.3.2 installed in /Application folder. The problem is only relative to open a new Terminal window (it works for, e.g., Visual Studio Code or Copy Path)
If the path of the Finder window with focus (or the selected folder) does not contain spaces everything works perfectly, both using toolbar icon and keyboard shortcut.
If the path instead contains spaces, then the keyboard shortcut does not work (while the toolbar icon still does work).

**Comment by Ji4n1ng** [comment]
The new version has been released. Please let me know if there is any bug.

**Comment by ioemilio** [comment]
That was fast! Thank you, working great now.
