### ISSUE TITLE
Support Android Studio

### ISSUE THREAD

**Issue by NamekMaster** [Ji4n1ng/OpenInTerminal#147]
## Summarize this feature
open the current directory or file in Android Studio.
## Why should this feature be included?
Android Studio is also Jetbrains app, I guess its easy to support just like others

**Comment by Ji4n1ng** [comment]
You can try to add it in custom apps. If it doesn't work, please tell me.

**Comment by Ji4n1ng** [comment]
[v2.3.6](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.6) has supported Android Studio. You can try it.
