### ISSUE TITLE
 Feature request

### ISSUE THREAD

**Issue by YeomanYe** [Ji4n1ng/OpenInTerminal#149]
Thank you very much for providing this tool, it is very useful for me.However, I think there are some imperfections. I would like to put forward some suggestions. I hope you don't mind my unfathomable ideas.

## Summarize this feature

I want to be able to launch more quickly through the toolbar icon, rather than clicking on the icon to appear a drop-down option at launch. Because there are only one or two features that my colleagues and I want to jump-start

## Why should this feature be included?

Because there are only one or two features that most people want to jump-start.

## Additional information

I think it can be done in two ways. 

- Split the drop-down options into individual ICONS
- Set mouse shortcuts
	- `Ctrl + Left Mouse`： open terminal
	- `Shift + Left Mouse`： open editor

**Comment by Ji4n1ng** [comment]
Maybe you can try OpenInTerminal-Lite and OpenInEditor-Lite.
