### ISSUE TITLE
Support wezterm

### ISSUE THREAD

**Issue by zhou13** [Ji4n1ng/OpenInTerminal#152]
## Summarize this feature

It would be nice if OpenInTerminal can support wezterm: https://github.com/wez/wezterm

## Why should this feature be included?

wezterm is a nice GPU-accelerated terminal emulator.

**Comment by lkhrs** [comment]
Adding WezTerm as a custom app doesn't work, here is a screenshot of the error:

<img width="372" alt="4TPfEb4p" src="https://user-images.githubusercontent.com/1342461/176952060-a67ba8b3-2523-4cb8-a9a9-dd9dca27ec40.png">

**Comment by Ji4n1ng** [comment]
This is supported in [v2.3.7](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.7).
