### ISSUE TITLE
Support Tabby

### ISSUE THREAD

**Issue by Felix2yu** [Ji4n1ng/OpenInTerminal#165]
## Summarize this feature
希望支持终端应用[Tabby](https://github.com/Eugeny/tabby)，尝试添加自定义菜单，仅能够打开应用并不会创建当前位置的终端

**Comment by vict0rsch** [comment]
I can see there's a merged PR for Tabby but I don't see it supported in the latest release (2.3.6). Is there a plan for it? Thanks!

**Comment by Ji4n1ng** [comment]
Hi @vict0rsch , yes, there will be an update next month.

**Comment by Elter71** [comment]
Are any upped about this?

**Comment by Ji4n1ng** [comment]
This is supported in [v2.3.7](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.7).
