### ISSUE TITLE
 OpenInTerminal 和 OpenInTerminal  Lite在打开"终端"的时候，会打开两个终端窗口

### ISSUE THREAD

**Issue by hzhgino** [Ji4n1ng/OpenInTerminal#166]
## What is the issue?
1.在通过OpenInTerminal 设置快捷键打开mac自带终端程序的时候。会打开两个终端窗口。
2.在使用OpenInTerminal  Lite 打开终端的时候，也会自动打开两个终端叉棍口
## How does one reproduce the issue?
1.关闭当前所有的终端（mac自带的终端）窗口（cmd+q）
2.通过OpenInTerminal设置的快捷键打开终端窗口，或者通过OpenInTerminal  Lite 的快捷方式打开终端窗口。
## Screenshots
![1](https://user-images.githubusercontent.com/23489321/156090937-de1eeaaa-3c9f-4a9d-9446-0180a162e758.png)

## Debug information (Logs, OS, Hardware, Version, etc.)
 OpenInTermina：v2.3.5 Latest 
 OpenInTerminal-Lite： v1.2.4
 OS：Catalina intel

**Comment by Ji4n1ng** [comment]
这个是macOS的bug，建议不要退出Terminal (Cmd + Q)，而是用 (Cmd + W) 关闭窗口。

https://github.com/Ji4n1ng/OpenInTerminal/issues/35
