### ISSUE TITLE
使用Jetbrains Toolbox安装的IDE（如IDEA等）无法被OpenInTerminal识别到

### ISSUE THREAD

**Issue by CaliInn-Li** [Ji4n1ng/OpenInTerminal#168]
## What is the issue?
使用Jetbrains Toolbox安装的IDE（如IDEA等）无法被OpenInTerminal识别到。这可能与Jetbrains Toolbox的默认安装路径有关。希望可以自定义扫描路径或者支持手动添加IDE路径。
## 有用的信息
Jetbrains Toolbox安装IDE的路径默认为/Users/xxx/Library/Application Support/JetBrains/Toolbox
## Screenshots
<img width="552" alt="截屏2022-03-11 上午9 07 28" src="https://user-images.githubusercontent.com/40906144/157782143-217937a7-8b06-4322-9eff-2f76dbf7f7eb.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS 12.2.1 (21D62), OpenInTerminal 2.3.5

**Comment by Ji4n1ng** [comment]
感谢建议，目前OpenInTerminal确实不会关注这个路径，可以先使用添加自定义应用功能，后续版本会考虑解决这个问题

**Comment by Ji4n1ng** [comment]
最新版本已经解决这个问题了，你可以试一下 https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.6
