### ISSUE TITLE
Fail to work on 12.2

### ISSUE THREAD

**Issue by qiulang** [Ji4n1ng/OpenInTerminal#169]
## What is the issue?

Fail to work on 12.2. When I click the button, no popup window

## Screenshots
<img width="798" alt="no popup" src="https://user-images.githubusercontent.com/516243/158060102-c8ededae-2b7e-4c95-bf87-beaa23f84aa6.png">

## Debug information (Logs, OS, Hardware, Version, etc.)

openinterminal: 2.3.5
MacBook Air (M1, 2020)
MacOS 12.2.1 (21D62)

**Comment by qiulang** [comment]
The one on the finder menu works though.
<img width="1188" alt="finder menu" src="https://user-images.githubusercontent.com/516243/158061928-1f759e32-a305-48a9-ab4b-a835e1a1b22a.png">

**Comment by molvqingtai** [comment]
same question

**Comment by Ji4n1ng** [comment]
I guess you have checked the "Apply to Finder Toolbar menu" option but didn't add any custom menu options in Preferences. You need to add something if you want to use custom menu.

**Comment by qiulang** [comment]
@Ji4n1ng I still can't make it work as I didn't check "Apply to Finder Toolbar menu" option. But even if I check it and add iTerm to it, it still doesn't work

<img width="529" alt="not checked" src="https://user-images.githubusercontent.com/516243/218972341-21959dc2-2aad-4956-82ba-90524ab6ab57.png">



<img width="443" alt="check" src="https://user-images.githubusercontent.com/516243/218972684-e8eb0065-21cf-4896-8f17-2b7da8a998c8.png">

**Comment by Ji4n1ng** [comment]
Hi @qiulang , please make sure that you have the permission checked in "Privacy & Security" -> "Extensions" -> "Added extensions" as shown in the below screenshot.

<img width="715" alt="Screenshot 2023-02-15 at 4 36 07 PM" src="https://user-images.githubusercontent.com/11001224/218975415-491138db-798b-475b-97e0-5e589e03937d.png">

Please note that OpenInTerminal won't work in the directories belong to OneDrive or Google Drive as only one Finder extension can work in the same directory.
