### ISSUE TITLE
Add Github Sponsor

### ISSUE THREAD

**Issue by sshquack** [Ji4n1ng/OpenInTerminal#171]
## What is the issue?
This is an amazing app and works beautifully on macOS Monterey 12.3. Thank you @Ji4n1ng !! ❤️ 

## How does one reproduce the issue?
Please add Github Sponsor for one-time donation. I don't have paypal or alipay.

## Screenshots
https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors

![Screenshot 000139@2x](https://user-images.githubusercontent.com/5678459/160917614-997113d6-30e5-4e63-9197-b0611d7c05eb.png)

## Debug information (Logs, OS, Hardware, Version, etc.)
❤️

**Comment by Ji4n1ng** [comment]
I have added GitHub Sponsor. Thank you very much for your kind support!
