### ISSUE TITLE
Alacritty not shown in macOS 12.3.1

### ISSUE THREAD

**Issue by tobx** [Ji4n1ng/OpenInTerminal#172]
## What is the issue?

The "Open In?" popup does not include Alacritty since minor upgrade to macOS Monterey 12.3.1 (I think)

## How does one reproduce the issue?

Hopefully this is reproducible by opening "OpenInTerminal-Lite" in macOS 12.3.1 for the first time.

## Screenshots

![screenshot](https://user-images.githubusercontent.com/6427718/163641246-4debda83-e58e-49f2-bbef-858fd9a1cf0b.png)

## Debug information (Logs, OS, Hardware, Version, etc.)

macOS Monterey 12.3.1
Alacritty 0.10.1
OpenInTerminal-Lite: 1.2.4

**Comment by Ji4n1ng** [comment]
Please check the Setting part of the [doc of OpenInTerminal-Lite](https://github.com/Ji4n1ng/OpenInTerminal/blob/master/Resources/README-Lite.md)

**Comment by tobx** [comment]
I am quite sorry, I did that before, I thought Alacritty was included in the dialog, but obviously I was wrong.

**Comment by dchakro** [comment]
It's the same on Catalina (10.15.7)

![SCR-20220707-rnr](https://user-images.githubusercontent.com/35454738/177828707-4f8b5a2f-ee63-42da-8c6a-a738d6593cf0.png)
