### ISSUE TITLE
Finder toolbar not working in Monterey

### ISSUE THREAD

**Issue by johnny-liang-gd** [Ji4n1ng/OpenInTerminal#178]
## What is the issue?
Tapping on OpenInTerminal in Finder toolbar has no response

## How does one reproduce the issue?
- Install in Monterey and running the app, enable the Finder extension and the app icon menu is visible
- Tapping on it

Actual: No terminal opened or dropdown menu appears
Expected: Dropdown menu should be visible and have the option to open either in VSCode or iTerm(I set the default terminal to iTerm)

## Screenshots
<img width="126" alt="image" src="https://user-images.githubusercontent.com/99311446/180909596-15b19ace-3f13-4fee-af9c-e3e4202ec6ea.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
Monterey 12.4

**Comment by johnny-liang-gd** [comment]
OK, figured out, i have to add the apps to the custom menu first, the `README.md` might want to add this step and highlight, coz I saw the same issues been reported as well before me

**Comment by qiulang** [comment]
I still don't know how to make it work. I didn't add apps to the custom menu .

<img width="529" alt="not check" src="https://user-images.githubusercontent.com/516243/218971404-78b88432-349f-4205-80f2-a5bf00b394b1.png">

But if I add it doesn't work too

<img width="443" alt="add iTerm" src="https://user-images.githubusercontent.com/516243/218971717-2f90c4f3-0ffa-47be-b6ed-b137c6bf9692.png">

**Comment by ApolloTang** [comment]
I am having the same problem. 
This is working on my old Intel MBP, but I am now installing it on a new Mac.  
Checking the "Apply to Finder Toolbar Menu" option does not place the OpenInterminal button on the Finder's toolbar. 

I am on Sequoia 15.1.1, M4max MacBook Pro.
