### ISSUE TITLE
请支持OneDrive中的右键菜单

### ISSUE THREAD

**Issue by s140335** [Ji4n1ng/OpenInTerminal#181]
在OneDrive文件夹下, Finder窗口右上角的下拉菜单有打开控制台等选项, 但是右键菜单没有. 

OneDrive自定义保存的文件夹是个alias, 源地址在~/Library/CloudStorage下, 但好像跟一般的文件夹不一样, 不知道FIFinderSyncController.default().directoryURLs应该怎么设置

**Comment by Ji4n1ng** [comment]
建议使用 OpenInTerminal-Lite。应该是访达扩展有冲突的，这个不是 OpenInTerminal 的问题。
