### ISSUE TITLE
Install on M1 Ventura

### ISSUE THREAD

**Issue by justdan0227** [Ji4n1ng/OpenInTerminal#185]
Is there a different set of steps to getting this in the finder toolbar on Ventura?  Did the brew install --cask openinterminal, and it shows up in the Applications folder, however, there is no icon in the finder toolbar.

**Comment by justdan0227** [comment]
Found it.. Under Ventura you have to go to Settings -> Privacy -> Others / Extension / Added Extensions and enable it there!

**Comment by khurshid-alam** [comment]
@justdan0227 I couldn't find it opening-terminal-lite in added extension. So how do I enable it ?
