### ISSUE TITLE
开启扩展后会导致finder侧边栏中外置硬盘图标显示错误

### ISSUE THREAD

**Issue by AbelChe** [Ji4n1ng/OpenInTerminal#187]
## What is the issue?
开启扩展后会导致finder侧边栏中外置硬盘图标显示错误

## How does one reproduce the issue?
在开启扩展的情况下，插入外置硬盘、u盘等，finder侧边栏的硬盘图标显示错误。

## Screenshots
开启扩展后图标显示错误
<img width="422" alt="image" src="https://user-images.githubusercontent.com/40518242/220803389-fdd4bc19-3302-409a-aae3-016f3257f17e.png">

关闭扩展并重启finder后恢复正常
<img width="394" alt="image" src="https://user-images.githubusercontent.com/40518242/220803746-6835c5ef-8fdb-4a16-8fee-3c5077e288f8.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
macbook pro 2019 16'
macOS Big Sur 11.6.3
OpenInTerminal 2.3.6

**Comment by Ji4n1ng** [comment]
macOS的问题，升级一下系统就好了
