### ISSUE TITLE
Show correct icon for Xcode

### ISSUE THREAD

**Issue by heiba** [Ji4n1ng/OpenInTerminal#189]
## Summarize this feature

In the custom menu options, when trying to Xcode as a shortcut, the icon in the context menu is incorrect, due to Xcode not being fully supported by OpenInTerminal.

See screenshot below

<img width="436" alt="image" src="https://user-images.githubusercontent.com/4654411/226237204-daa89294-e243-47be-b557-d0f919f2df87.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/4654411/226237249-77aa4643-4651-4442-9ea2-73255336d6ee.png">

<img width="198" alt="image" src="https://user-images.githubusercontent.com/4654411/226236905-32378a16-8ef1-4b40-836e-8ca4cdca3cea.png">

## Why should this feature be included?

Xcode is the most popular IDE on Mac OS and used by anyone developing an iOS application. The icon needs to show-up correctly in the context menu.

**Comment by Ji4n1ng** [comment]
This is supported in [v2.3.7](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.7).
