### ISSUE TITLE
能否支持下Wrap终端

### ISSUE THREAD

**Issue by ijinfeng** [Ji4n1ng/OpenInTerminal#193]
## Summarize this feature
支持Wrap支持的唤起等行为

## Why should this feature be included?
Wrap终端用户交互更加友好

## Additional information
Wrap介绍：https://docs.warp.dev/getting-started/readme

**Comment by kingzzz123** [comment]
可以使用右键在桌面快速打开warp，但是每次打开两个窗口

**Comment by TerminaD** [comment]
Same feature suggestion

**Comment by dacaiguoguo** [comment]
https://github.com/Mortennn/FiScript.git and refers to it as a temporary solution.

**Comment by Ji4n1ng** [comment]
This is supported in [v2.3.7](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.7).
