### ISSUE TITLE
未能打开文稿“桌面”。“文本编辑”打不开格式为“文件夹”的文件。

### ISSUE THREAD

**Issue by hoochanlon** [Ji4n1ng/OpenInTerminal#194]
macOS12

![catch2023-06-10 23 38 38](https://github.com/Ji4n1ng/OpenInTerminal/assets/35732922/795af27f-6cf8-4d18-9545-8e5a21df4d78)

**Comment by Ji4n1ng** [comment]
把默认的编辑器改成支持打开文件夹的编辑器，例如VSCode等
