### ISSUE TITLE
Can't Configure To Open iTerm

### ISSUE THREAD

**Issue by haohu321** [Ji4n1ng/OpenInTerminal#197]
## What is the issue?
After installing OpenInTerminal, I can't configure it to open with iTerm by default. Even though I've set iterm2 to be my default terminal. There was no prompt asking me to pick the default terminal either.

## How does one reproduce the issue?
1. Install OpenInTerminal extension on macOS Ventura 13.4
2. Open in terminal

## Screenshots
![image](https://github.com/Ji4n1ng/OpenInTerminal/assets/25491828/7d1b88ae-4071-4ea5-a7f9-64581c7bb730)

## Debug information (Logs, OS, Hardware, Version, etc.)
As specified above.

**Comment by sudoyang** [comment]
I have got the same issue.

**Comment by Ji4n1ng** [comment]
BTW, the Preferences is here
<img width="251" alt="Screenshot 2023-08-30 at 9 16 59 PM" src="https://github.com/Ji4n1ng/OpenInTerminal/assets/11001224/5733ecde-a840-440b-9162-271a528be04c">

**Comment by sudoyang** [comment]
It worked, thanks! @Ji4n1ng
