### ISSUE TITLE
Release Version Update

### ISSUE THREAD

**Issue by magicwenli** [Ji4n1ng/OpenInTerminal#198]
## Summarize this feature

I noticed that wezterm support has been merged at #177 , but it seems that this feature wasn't included by currently release. [v2.3.6](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.6)

Could you please release new version of OpenInTerminal?

thanks!

**Comment by Ji4n1ng** [comment]
This is supported in [v2.3.7](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.7).
