### ISSUE TITLE
icon in finder toolbar is not working

### ISSUE THREAD

**Issue by NYDHRSY** [Ji4n1ng/OpenInTerminal#202]
## What is the issue?

The icon dosen't show any interface when clicking in finder toolbar. 

## How does one reproduce the issue?

I tried reinstall the app several times, from release page or brew.

## Screenshots

![image](https://github.com/Ji4n1ng/OpenInTerminal/assets/56386116/8df4fbf5-84b8-4a9a-8eba-3a36451dc4cf)

## Debug information (Logs, OS, Hardware, Version, etc.)

MacOS 13.6 (22G120)

**Comment by Ji4n1ng** [comment]
Please check https://github.com/Ji4n1ng/OpenInTerminal/issues/169#issuecomment-1104953522

**Comment by NYDHRSY** [comment]
> Please check [#169 (comment)](https://github.com/Ji4n1ng/OpenInTerminal/issues/169#issuecomment-1104953522)请查看#169（评论）

Yes, I've checked the issue before I opened this issue.
I do give the permission and here is the screenshot:
![image](https://github.com/Ji4n1ng/OpenInTerminal/assets/56386116/d3fb9f11-aa7f-4f41-8ec7-6ddfab0f6bae)

**Comment by Ji4n1ng** [comment]
Not the permission issue. The following one:
> I guess you have checked the "Apply to Finder Toolbar menu" option but didn't add any custom menu options in Preferences. You need to add something if you want to use custom menu.
