### ISSUE TITLE
[FR] support kitty to open in existing instance new tabs instead of new instance window

### ISSUE THREAD

**Issue by truebit** [Ji4n1ng/OpenInTerminal#203]
## Summarize this feature

launch kitty in one instance new tab instead of new instance  new windows

## Why should this feature be included?

We would like to open kitty terminal in one instance instead of multiple instance windows

## Additional information
kitty could be opened with single instance with `-1 --instance-group xxx` parameters.

**Comment by Ji4n1ng** [comment]
This is supported in [v2.3.7](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/v2.3.7).

**Comment by jqtmviyu** [comment]
* Bug: 
Still opening a new window.

* Version: 
Kitty 0.32.1
OpenInTerminal 2.3.7

* Reference Links: 

>--instance-group <INSTANCE_GROUP>
>    Used in combination with the [kitty --single-instance](https://sw.kovidgoyal.net/kitty/invocation/#cmdoption-kitty-single-instance) option. All kitty invocations with the same [kitty --instance-group](https://sw.kovidgoyal.net/kitty/invocation/#cmdoption-kitty-instance-group) will result in new windows being created in the first kitty instance within that group.

* My solution

1.  add Kitty config

`~/.config/kitty/kitty.conf`

```
allow_remote_control yes
listen_on unix:/tmp/kitty
```

2. add Automator.app

```
#!/bin/sh
exit=$(ls /tmp | grep '^kitty')

if [ $exit ]; then
  sock="unix:/tmp/$exit"
  /usr/local/bin/kitty @ --to $sock launch --type=tab --cwd $1 --no-response && open -a kitty
else
  open -a kitty --args $1
fi
```

**Comment by tim-hilde** [comment]
The core issue of the current workings is that opening a directory via the app results in a new kitty app instance. This results in two apps open. 
The tab thing is something unrelated to the problem.

**Comment by a-b** [comment]
@Ji4n1ng is it possible to implement a new feature so user can pass custom parameters to kitty?
