### ISSUE TITLE
Can't launch 2.3.7 on M3 iMac

### ISSUE THREAD

**Issue by JuanCab** [Ji4n1ng/OpenInTerminal#207]
## What is the issue?

Any attempt to launch OpenInTerminal 2.3.7 results in a failure on my M3 iMac running macOS 14.2.1. 

## How does one reproduce the issue?

Download ZIP file of 2.3.7 and unzip, then double-clock on OpenInTerminal, it fails to launch with two errors:

"The application “OpenInTerminal.app” can’t be opened."

and

"“OpenInTerminal.app” can’t be opened because Apple cannot check it for malicious software."

When I hold control key to launch from contextual menu, I still get the same errors.  Version 2.3.6 has no issues. 

Let me know if there is other information which would help diagnose this.

**Comment by ViscousLoser** [comment]
I am having the same issue on an M1 MacbookPro with both the brew cask and the zip installs. Double-clicking the app in the finder returns a popup with the text: "The application “OpenInTerminal.app” can’t be opened"; and 
open -a openinterminal.app returns:
The application /Applications/OpenInTerminal.app cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x60000147e2e0 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

**Comment by ijinfeng** [comment]
我的iMac上也报了同样的问题，我现在换回 v2.3.7就好了

**Comment by Ji4n1ng** [comment]
Hi guys, I have uploaded the re-signed apps in releases. Please let me know if there is still any problem.
