### ISSUE TITLE
Wrong signing in version OpenInTerminal v2.3.7 and OpenInTerminal-Lite 1.2.6

### ISSUE THREAD

**Issue by suschizu** [Ji4n1ng/OpenInTerminal#208]
## What is the issue?
the downloads now contain a development signature:
EXPECTED 'Jianing Wang (Q33U8R4U57)' but FOUND 'Apple Development: Jianing Wang (USNKC8GGZ6)

## How does one reproduce the issue?
not possible to open apps

**Comment by vtu-dog** [comment]
If you'd like to run the app as-is without waiting for a developer response, you can bypass this issue by forcefully signing the app yourself:
```bash
codesign --force --deep --sign - /Applications/OpenInTerminal.app
```
Still, a proper resolution would be most welcome :)

**Comment by Ji4n1ng** [comment]
Hi guys, I have uploaded the re-signed apps in releases. Please let me know if there is still any problem.

**Comment by suschizu** [comment]
hey @Ji4n1ng - thanks for the quick fix! I can confirm that all 2 downloads now contain:
Developer ID Application: Jianing Wang (Q33U8R4U57) again :) 
happy new year!
