### ISSUE TITLE
建议：可以做成不清屏吗？

### ISSUE THREAD

**Issue by UniqueSimon** [Ji4n1ng/OpenInTerminal#3]
如题，发现打开的时候是cd+clear，终端一开始的信息就被清空了。
cdto的是不清屏的。
![清屏.gif](https://i.loli.net/2019/04/17/5cb6c777f0ae0.gif)

**Comment by Ji4n1ng** [comment]
好的，记下来了。非常抱歉带来了糟糕的体验。

**Comment by Ji4n1ng** [comment]
看到这条 issue 的朋友，非常欢迎你来留言。cd 之后 clear 是否需要？如果没必要，就都不 clear 了。如果有必要，我就加一个可供用户设置的命令。

**Comment by UniqueSimon** [comment]
@Ji4n1ng cdto的好像是没有cd，直接打开路径的。谢谢。

**Comment by Ji4n1ng** [comment]
@UniqueSimon 那就直接取消吧。下个版本会更新 😃

**Comment by Ji4n1ng** [comment]
[v0.2.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.2.0) 已解决。

**Comment by alphatr** [comment]
加一个可供设置的命令麻烦么？希望有清屏的选项，或者可以扩展个 shell 脚本的 hook

**Comment by Ji4n1ng** [comment]
@alphatr 可以加。等后续版本更新吧。`OpenInTerminal-Lite` 未来只会提供是否清屏的命令行设置。后续`OpenInTerminal` 会有设置面板 GUI。在打开终端之后执行用户自定义命令这一功能，可以考虑，感觉是个不错的功能。
