### ISSUE TITLE
macOS 10.14.4安装后finder里面没有出现OpenInTerminal图标

### ISSUE THREAD

**Issue by man2018** [Ji4n1ng/OpenInTerminal#31]
## What is the issue?
macOS 10.14.4安装后finder里面没有出现OpenInTerminal图标

## How does one reproduce the issue?
我是2018款顶配macbook pro，10.14.4系统，正常安装后不出来
## Debug information (Logs, OS, Hardware, Version, etc.)
<img width="870" alt="12" src="https://user-images.githubusercontent.com/18020785/57291584-50b5d080-70f2-11e9-855e-8ef0a141e483.png">

**Comment by Ji4n1ng** [comment]
@man2018 请检查 Finder 扩展权限打开了没有。

具体的文档在这里 https://github.com/Ji4n1ng/OpenInTerminal/blob/master/README-zh.md#2-%E6%89%93%E5%BC%80-finder-%E6%89%A9%E5%B1%95%E6%9D%83%E9%99%90

**Comment by man2018** [comment]
> @man2018 请检查 Finder 扩展权限打开了没有。
> 
> 具体的文档在这里 https://github.com/Ji4n1ng/OpenInTerminal/blob/master/README-zh.md#2-%E6%89%93%E5%BC%80-finder-%E6%89%A9%E5%B1%95%E6%9D%83%E9%99%90

已搞定 🙏🏻
