### ISSUE TITLE
i added the shortcut in finder toolbar, but it can't open terminal or the editor. it looks like to open itself again

### ISSUE THREAD

**Issue by LuKun85** [Ji4n1ng/OpenInTerminal#33]

**Comment by Ji4n1ng** [comment]
@LuKun85 
Please check if there is an OpenInTerminal(main app) icon in the status bar. The Finder Extension will always be in the toolbar. But if the main app is not open, it will not work. It is recommended to set OpenInTerminal to launch at login in Preferences.
