### ISSUE TITLE
Support VScodium

### ISSUE THREAD

**Issue by PascalLeMerrer** [Ji4n1ng/OpenInTerminal#34]
## Summarize this feature
Add the support of [VSCodium](https://vscodium.com/) as an editor

## Why should this feature be included?
I switched from VScode to VScodium recently... Maybe I'm not the only one?

## Additional information
VSCodium is built from the sources of VSCode, but it excludes Microsoft trackers.
It is almost identical to VScode, so it should be easy to integrate.

**Comment by Ji4n1ng** [comment]
@PascalLeMerrer OpenInTerminal will add this feature in next version. Thank you for your advice.

**Comment by Ji4n1ng** [comment]
@PascalLeMerrer OpenInTerminal v0.10.0 now supports VSCodium.

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.10.0

**Comment by PascalLeMerrer** [comment]
It has been quick!

thanks @Ji4n1ng
