### ISSUE TITLE
open just one terminal window

### ISSUE THREAD

**Issue by onceSS** [Ji4n1ng/OpenInTerminal#35]
## Summarize this feature
openinterminal/openinterminal-lite will open two windows of terminal,   
how can I get just one window with the specified url.

## 中文
openinterminal/openinterminal-lite 会打开两个terminal窗口，其中一个是默认地址的，第二才是指定地址的terminal窗口，怎样才能只打开需要的指定地址的窗口？

**Comment by Ji4n1ng** [comment]
@onceSS 
This problem usually occurs when the Terminal is first started. So you can use ⌘W to close Terminal window instead of using ⌘Q to quit Terminal.

这个问题只发生在第一次启动 Terminal 的时候。所以，你可以通过 ⌘W 来关闭 Terminal 的窗口，而不是用 ⌘Q 来退出 Terminal。

**Comment by gee1k** [comment]
@Ji4n1ng 我记得之前的版本是没有这个问题的，最近更新新版后才是这样的

**Comment by Ji4n1ng** [comment]
@gee1k 这个问题只在 Mojave 上有，这个不是应用的问题，是系统的问题。
