### ISSUE TITLE
use `open` to handle iTerm

### ISSUE THREAD

**Issue by pynixwang** [Ji4n1ng/OpenInTerminal#36]
## Summarize this feature

```swift
import Foundation

final class iTermApp: Terminal {
    
    func open(_ path: String, _ newOption: NewOptionType, _ clear: ClearOptionType) throws {
        
        guard let url = URL(string: path) else {
            throw OITError.wrongUrl
        }
        
        let source = """
            tell application "iTerm"
                open "\(url.path)"
            end tell
            """
        
        let script = NSAppleScript(source: source)!
        
        var error: NSDictionary?
        
        script.executeAndReturnError(&error)
        
        if error != nil {
            throw OITError.cannotAccessIterm
        }
    }
    
}
```
## Why should this feature be included?

remove ugly cd command

## Additional information

drawback:
new window or tab must be configure via iTerm

**Comment by Ji4n1ng** [comment]
@pynixwang These features(open with a new window or tab) were proposed by the previous issues. It's hard to meet everyone, because some people like it, while others don't. So even though the code looks bad, at least it works. If you could meet these needs with more elegant codes, please let me know.

**Comment by pynixwang** [comment]
@Ji4n1ng  not code looks bad.
it 's the `cd xxx` command

**Comment by pynixwang** [comment]
when I launch the terminal.

**Comment by pynixwang** [comment]
I do not konow why iTerm not expose `directory` to scriptable api.

**Comment by Ji4n1ng** [comment]
@pynixwang You can set it to execute `clear` after launching the terminal.

**Comment by pynixwang** [comment]
I know this feature, but it left more useless history.

**Comment by pynixwang** [comment]
![Screen Recording 2019-05-26 at 7 49 53 PM](https://user-images.githubusercontent.com/1189879/58381521-90d0ea80-7ff0-11e9-8804-1606dab15925.gif)

**Comment by pynixwang** [comment]
works as I expect.

**Comment by Ji4n1ng** [comment]
@pynixwang I have the code you provided. It seems that it will open a new tab if there is already a window opened. I will use this code to replace the `open a new tab` part. This will not have `cd xxx` in history. And the `open a new window` part remains the same.

**Comment by Ji4n1ng** [comment]
@pynixwang Thank you for your suggestions! 😀

**Comment by pynixwang** [comment]
@pynixwang no, this is control by an iTerm setting
<img width="1018" alt="WX20190526-200356@2x" src="https://user-images.githubusercontent.com/1189879/58381612-6fbcc980-7ff1-11e9-8b34-a3db451c08c5.png">

**Comment by pynixwang** [comment]
so setting should do a callback to set iTerm 's defaults.

**Comment by Ji4n1ng** [comment]
@pynixwang Oh I see. I will look into this. It is best to set iTerm 's defaults.

**Comment by pynixwang** [comment]
```
tell application "XXX"
	open "path"
end tell
```

this pattern works with Terminal, iTerm, Sublime Text and Visual Studio Code.

others not installed.

**Comment by pynixwang** [comment]
maybe all Cocoa Applications confirm to `open`

**Comment by Ji4n1ng** [comment]
OpenInTerminal-Lite v0.4.4 has solved the problem.

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.4.4

You can use the below command to set iTerm.

```
# Open a new Tab
defaults write com.googlecode.iterm2 OpenFileInNewWindows -bool false
# Open a new Window
defaults write com.googlecode.iterm2 OpenFileInNewWindows -bool true
```
