### ISSUE TITLE
use `agent` to prevent Dock flash

### ISSUE THREAD

**Issue by pynixwang** [Ji4n1ng/OpenInTerminal#37]
## Why should this feature be included?

Dock icon flash is bad.

**Comment by pynixwang** [comment]
in Lte version

**Comment by Ji4n1ng** [comment]
Hi, @pynixwang. I don't understand the meaning of the `agent`. Could you give me a more detailed explanation about it?

**Comment by pynixwang** [comment]
![image](https://user-images.githubusercontent.com/1189879/58381639-e4900380-7ff1-11e9-9942-4caf72449cdb.png)

set this flag, no icon flash on Dock.

**Comment by Ji4n1ng** [comment]
@pynixwang I see. The next version will solve this. Thanks a lot!

**Comment by Ji4n1ng** [comment]
OpenInTerminal-Lite v0.4.4 has solved the problem.

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.4.4
