### ISSUE TITLE
The item does not appear if in other diskpart.

### ISSUE THREAD

**Issue by lpf-gavin** [Ji4n1ng/OpenInTerminal#39]
<img width="255" alt="屏幕快照 2019-06-06 19 41 43" src="https://user-images.githubusercontent.com/24205102/59030289-2abb5180-8893-11e9-876b-be916be71bb1.png">
<img width="230" alt="屏幕快照 2019-06-06 19 41 59" src="https://user-images.githubusercontent.com/24205102/59030294-2d1dab80-8893-11e9-962c-cdc5138f6c1f.png">
The first image is captured in main diskpart, and the second in /Volumes/diskname/foldername?

**Comment by Ji4n1ng** [comment]
@lpf-gavin I will look into this.

**Comment by lpf-gavin** [comment]
so quickly,thanks


 
---Original---

**Comment by Ji4n1ng** [comment]
@lpf-gavin OpenInTerminal v0.10.2 has solved this problem. If you have any question, please let me know.

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.10.2
