### ISSUE TITLE
重装后无法打开应用

### ISSUE THREAD

**Issue by wyibo** [Ji4n1ng/OpenInTerminal#40]

**Comment by ys-xue** [comment]
+1，系统也是10.14.5，用`brew cask reinstall`了之后还是没法打开

**Comment by Ji4n1ng** [comment]
感谢反馈，我去看一下这个问题。

**Comment by molvqingtai** [comment]
同样的问题

**Comment by mataotao** [comment]
+1 重启后就打不开了，重装也打不开

**Comment by Ji4n1ng** [comment]
你们可以把之前的删掉，然后用下面这个。

[app.zip](https://github.com/Ji4n1ng/OpenInTerminal/files/3343656/app.zip)

检查下面有没有权限。

![5EC9046E1AE59D7143387C467461FDCC](https://user-images.githubusercontent.com/11001224/60406022-59a0bb00-9be6-11e9-8860-23247162767e.jpg)

**Comment by Ji4n1ng** [comment]
可以运行的话，请告诉我，谢谢

**Comment by Ji4n1ng** [comment]
现在可能会报权限问题，记得打开一下。

<img width="532" alt="屏幕快照 2019-07-01 10 01 14" src="https://user-images.githubusercontent.com/11001224/60406211-5c4fe000-9be7-11e9-9914-09c61f7b1939.png">

<img width="780" alt="屏幕快照 2019-07-01 10 01 28" src="https://user-images.githubusercontent.com/11001224/60406214-5eb23a00-9be7-11e9-950e-4d2d6dc3dec0.png">

**Comment by Ji4n1ng** [comment]
你们可以用 OpenInTerminal v0.4.5 试一下。如果有问题请告诉我，非常感谢！

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.4.5

**Comment by gee1k** [comment]
OpenInTerminal 打不开

**Comment by Ji4n1ng** [comment]
@gee1k 删掉之前的，用 0.10.3

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.10.3

**Comment by gee1k** [comment]
brew 更新了吗？

**Comment by Ji4n1ng** [comment]
@gee1k brew 还没有，一会提交审核。非常抱歉带来了不便

**Comment by mataotao** [comment]
> @gee1k 删掉之前的，用 0.10.3
> 
> https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.10.3

这个没问题

**Comment by gee1k** [comment]
@Ji4n1ng 没关系，我昨天打包app的时候也反了个低级错误😰

https://github.com/gee1k/uPic

**Comment by Ji4n1ng** [comment]
@mataotao 好的，非常抱歉带来了不便

**Comment by Ji4n1ng** [comment]
@gee1k 你这个程序不错

**Comment by gee1k** [comment]
@Ji4n1ng 你这个软件也很好用👍，从你刚发布开始就在用了

**Comment by Ji4n1ng** [comment]
@gee1k 谢谢支持！😀

**Comment by Ji4n1ng** [comment]
OpenInTerminal-Lite [v0.4.5](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.4.5) 和 OpenInTerminal [v0.10.3](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/0.10.3) 可以用了。

现在 brew 已更新。

**Comment by RitterHou** [comment]
通过 `brew cask install openinterminal` 安装之后单击应用打开，没有弹出任何窗口，在资源管理器中看到进程是存在的

**Comment by Ji4n1ng** [comment]
@RitterHou 可以 `brew cask upgrade`，也可以卸载重装，记得清理一下回收站。

如果你用的是 OpenInTerminal，单击应用就只是启动了应用（顶部状态栏有图标），需要在 Finder 里面选择打开终端等操作，才可以弹出终端等。

当前的版本 UI 发生了变化，如果和图片不符合，按住 Option 右击 Finder，选择重新开启。

<img width="174" alt="2" src="https://user-images.githubusercontent.com/11001224/61678730-5193f100-ad36-11e9-9bd0-4388ce5b5315.png">

**Comment by RitterHou** [comment]
原来是在状态栏上面，谢谢之前没找到

**Comment by Ji4n1ng** [comment]
@RitterHou 不客气

**Comment by RitterHou** [comment]
单击状态栏上的图标可以打开iTerm2，但是把图标拖到finder上之后，单击finder上的图标没有打开终端

**Comment by Ji4n1ng** [comment]
你说这个方式是 OpenInTeminal-Lite 的。具体方式在 Readme 里有详细介绍，有中文文档。这两个应用是有区别的。
