### ISSUE TITLE
Finder context menu icon

### ISSUE THREAD

**Issue by grylem** [Ji4n1ng/OpenInTerminal#42]
Please add icon for context menu like
![example](https://user-images.githubusercontent.com/16815041/60755743-695c3d00-9ff4-11e9-9613-148104abfdc3.png)

**Comment by Ji4n1ng** [comment]
@grylem Good suggestion! This feature will be added in next version.

**Comment by Camji55** [comment]
@Ji4n1ng I believe I had this implemented in the past 🤷‍♂ Shouldn't be too difficult to implement.

**Comment by Ji4n1ng** [comment]
@Camji55 Of course. 😀

**Comment by Camji55** [comment]
Yeah, this is already implemented.

![Screen Shot 2019-07-09 at 10 22 41 AM](https://user-images.githubusercontent.com/2769158/60909632-977b9000-a233-11e9-9cf4-626f3e32d602.png)

**Comment by Ji4n1ng** [comment]
@Camji55 Yes. The only thing I need to do is to add an icon.

**Comment by Camji55** [comment]
@Ji4n1ng I completely misread this... I thought it was just adding the items, not the icons 💀

**Comment by Ji4n1ng** [comment]
@grylem OpenInTerminal [v2.0.1](
https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.0.1
) has supported this feature. It looks like this:

<img width="219" alt="1" src="https://user-images.githubusercontent.com/11001224/61589765-93f7e980-abe1-11e9-9eda-0ac2938aecf0.png">

**Comment by superlevure** [comment]
Hi, 

Is there any way to change the displayed icons ? 

For example I'd like to show VSCode's icon instead of the current one
