### ISSUE TITLE
Fix forcing use of /Applications directory

### ISSUE THREAD

**Issue by exiva** [Ji4n1ng/OpenInTerminal#43]
## What is the issue?
Currently OpenInTerminal assumes the application path only to be /Applications, and does not use the Applications folder in the users home directory resulting in it thinking the applications (Atom, iTerm, VSCode, etc) aren't installed.

https://github.com/Ji4n1ng/OpenInTerminal/blob/926a0633f3a054ff8a80ad2ef9c8bca2ccb2666d/OpenInTerminalCore/FinderManager.swift#L83

seems to be the issue where it's hardcoded to use /Applications

**Comment by Ji4n1ng** [comment]
@exiva Yes. It's a problem. I'll will try to solve it by checking both `/Applications` and Applicationds folder in the users home direcotory. Thank you for your good suggestion!

**Comment by Ji4n1ng** [comment]
@exiva OpenInTerminal [v2.0.1](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.0.1) and OpenInTerminal-Lite [v1.0.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.0.0) have fixed this bug.
