### ISSUE TITLE
Support for bbedit as a text editor

### ISSUE THREAD

**Issue by michaelcap** [Ji4n1ng/OpenInTerminal#44]

**Comment by Ji4n1ng** [comment]
@michaelcap The next version will support this feature.

**Comment by Ji4n1ng** [comment]
@michaelcap OpenInTerminal [v2.0.1](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.0.1) and OpenInEditor-Lite [v1.0.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.0.0) have supported this feature.

**Comment by Ji4n1ng** [comment]
@michaelcap You can use the below command to set BBEdit as the default editor.

```
defaults write wang.jianing.OpenInEditor-Lite OIT_EditorBundleIdentifier BBEdit 
```

**Comment by michaelcap** [comment]
Awesome!  Thanks!

Mike

**Comment by arichar6** [comment]
Hi, I tried the `defaults write` command above, and OIT Editor still opens VSCode (the one I selected originally). This is the case even after restarting the Finder. If I do `defaults read wang.jianing.OpenInEditor-Lite OIT_EditorBundleIdentifier` I get `BBEdit`. Do you know what might be happening? How do I get it to use BBEdit?

**Comment by Ji4n1ng** [comment]
Hi @arichar6 , you could try to use this one: `defaults write wang.jianing.app.OpenInEditor-Lite OIT_EditorBundleIdentifier BBEdit` (there is `.app` in it). And the doc is https://github.com/Ji4n1ng/OpenInTerminal/blob/master/Resources/README-Lite.md

**Comment by arichar6** [comment]
That works, thank you! Sorry I missed the documentation page... my mistake. 😖
