### ISSUE TITLE
不支持 Visual Studio Code Insiders 版本

### ISSUE THREAD

**Issue by Jackeriss** [Ji4n1ng/OpenInTerminal#46]
我安装了 Visual Studio Code Insiders 版本，但是提示我 Visual Studio Code 未安装

**Comment by Ji4n1ng** [comment]
Insiders 和正式版确实不是一个应用，下一个版本就支持 Insiders

**Comment by stevewyl** [comment]
我重新安装了vscode的stable最新版本 还是显示vscode未安装

**Comment by Ji4n1ng** [comment]
@stevewyl 你的 VSCode 在哪个路径，应用名称是什么

**Comment by stevewyl** [comment]
@Jackeriss 好了 重启了一次好了 可能是旧版本没卸载掉

**Comment by Camji55** [comment]
@stevewyl Were you able to get this resolved?

**Comment by Ji4n1ng** [comment]
@Jackeriss 新版本已支持 Visual Studio Code - Insiders

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.0.2

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.0.1
