### ISSUE TITLE
“OpenInTerminal” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by kid1412621** [Ji4n1ng/OpenInTerminal#47]
## What is the issue?
cannot open due to security issue
## Screenshots
<img width="422" alt="image" src="https://user-images.githubusercontent.com/26278054/61952264-f556f880-afe5-11e9-8311-4bfbabbb863c.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
Latest stable version(app and sys)

**Comment by Camji55** [comment]
@kid1412621 To resolve this issue, please do the following:
1. Open `System Preferences`
2. Click `Security & Privacy`
3. At the bottom of the window, there should be a button to allow the opening of `OpenInTermninal`.

**Comment by kid1412621** [comment]
Will it have no workaround method available in the future?

Cameron Ingham <notifications@github.com> 于2019年7月27日周六 上午1:15写道：

**Comment by Camji55** [comment]
@kid1412621 I'm not sure of the signing and distribution methods in the future will be. I wouldn't worry about it too much as the project is open source.

**Comment by kid1412621** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/26278054/61993859-c489c880-b0a4-11e9-8050-0776942b89df.png">
Cannot find that button

**Comment by Camji55** [comment]
@kid1412621 It would be on the `General` tab.

**Comment by kid1412621** [comment]
wow, it hide so deep. Only if u r on that page and opening the app, it will show. Thx.
