### ISSUE TITLE
菜单风格和系统保持一致

### ISSUE THREAD

**Issue by ibreathebsb** [Ji4n1ng/OpenInTerminal#48]
<img width="273" alt="屏幕快照 2019-08-02 23 02 54" src="https://user-images.githubusercontent.com/8876258/62379592-d6bea780-b579-11e9-86ef-48a6750da905.png">

建议图标设置为白色

**Comment by Ji4n1ng** [comment]
@ibreathebsb 好建议！忘了看看 dark mode 下的样子。。下个版本会解决

**Comment by Ji4n1ng** [comment]
@ibreathebsb OpenInTerminal 2.0.3 版本已解决这个问题。
