### ISSUE TITLE
Support TextMate as an editor

### ISSUE THREAD

**Issue by gingerbeardman** [Ji4n1ng/OpenInTerminal#49]
## Summarize this feature

Add the support of [TextMate](https://macromates.com) as an editor

## Why should this feature be included?

TextMate is still the fastest editor to open on my Mac, so I often use it to view things quickly.

## Additional information

https://macromates.com

**Comment by Ji4n1ng** [comment]
@gingerbeardman The next version will support this feature.

**Comment by gingerbeardman** [comment]
Actually, FWIW I'm now using the OpenInTerminal-Lite version.

**Comment by Ji4n1ng** [comment]
@gingerbeardman OpenInTerminal [2.0.4](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.0.4) and OpenInEditor-Lite [1.0.2](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.0.2) have supported this feature.

**Comment by gingerbeardman** [comment]
Thanks!
