### ISSUE TITLE
iTerm2 打不开

### ISSUE THREAD

**Issue by kbk01** [Ji4n1ng/OpenInTerminal#5]
iTerm2 打不开 自带终端可以正常使用 感谢作者

**Comment by Ji4n1ng** [comment]
可能是没有权限。去 系统设置 -> 安全性与隐私 -> 隐私 -> 自动化，查看 OpenInTerminal.app 有没有 iTerm.app 的权限。

**Comment by kbk01** [comment]
> 可能是没有权限。去系统设置 - >安全性与隐私 - >隐私 - >自动化，查看OpenInTerminal.app有没有iTerm.app的权限。

拥有权限呀

**Comment by Ji4n1ng** [comment]
你方便截个图看看吗？像这样

<img width="351" alt="1" src="https://user-images.githubusercontent.com/11001224/56294576-daaaf300-615d-11e9-8c12-13a0b5f4c109.png">

**Comment by kbk01** [comment]
我的open 只有finder的权限，怎么添加iTerm2的权限

**Comment by Ji4n1ng** [comment]
可能是第一次弹出权限框的时候，你手滑点了拒绝。你可以尝试删掉应用重新安装一下。

**Comment by kbk01** [comment]
重装以后没有弹出权限窗口呀

**Comment by Ji4n1ng** [comment]
在终端中执行

```
tccutil reset AppleEvents
```

然后，重新运行应用，重新授权。

**Comment by kbk01** [comment]
重新授权后也只能对访达控制 ，没有iTerm 2  还是打不开
<img width="1680" alt="屏幕快照 2019-04-18 下午7 49 51" src="https://user-images.githubusercontent.com/36129727/56359079-266ba400-6213-11e9-8049-7aa92c779b90.png">

**Comment by kbk01** [comment]
重新授权以后还是只有访达的控制 没有iTerm2的控制权限 
<img width="780" alt="屏幕快照 2019-04-18 下午7 49 54" src="https://user-images.githubusercontent.com/36129727/56359195-70548a00-6213-11e9-8529-13f3d5ef3098.png">

**Comment by Ji4n1ng** [comment]
你用的是哪一个版本？现在 v0.2.0 可以选择默认终端。建议你用 v0.2.0，这是最新版本。首先会选择默认终端，选择 iTerm2，然后会询问权限。
<img width="503" alt="屏幕快照 2019-04-18 19 55 38" src="https://user-images.githubusercontent.com/11001224/56359424-20c28e00-6214-11e9-939d-3ac72bf71fae.png">


<img width="420" alt="屏幕快照 2019-04-18 19 55 44" src="https://user-images.githubusercontent.com/11001224/56359438-27510580-6214-11e9-8411-c8a881e9fca2.png">

**Comment by kbk01** [comment]
我现在的版本v0.2.0 选择iTerm2 后并没有出来这张图的情况。打不开iTerm2选择自带终端可以打开

![](https://user-images.githubusercontent.com/11001224/56359438-27510580-6214-11e9-8411-c8a881e9fca2.png)

**Comment by Ji4n1ng** [comment]
那就奇怪了。难道你的 iTerm 是别人重打包的吗。方便的话，建议去官网 https://www.iterm2.com/ 下载，删除并替换原来的 iTerm。然后执行

```
defaults remove wang.jianing.OpenInTerminal OIT_TerminalBundleIdentifier
```

重新运行 OpenInTerminal，选择 iTerm2 试试。

**Comment by kbk01** [comment]
找到原因了，我的原版本是命名是 iTerm 2（官网下载的不知道为啥命名 iTerm 2）刚刚从新下载了一份这回是iTerm
可以正常使用了（太棒了，感谢🙏
<img width="231" alt="屏幕快照 2019-04-18 下午8 19 45" src="https://user-images.githubusercontent.com/36129727/56360578-b4e22480-6217-11e9-8f1a-aa78120b45f0.png">

**Comment by kbk01** [comment]
<img width="780" alt="屏幕快照 2019-04-18 下午8 23 52" src="https://user-images.githubusercontent.com/36129727/56360663-ea870d80-6217-11e9-9f04-37157e68691c.png">

**Comment by Ji4n1ng** [comment]
不客气，很高兴能帮到你
