### ISSUE TITLE
OpenTerminal-Lite - Open 2 tabs with iTerm 3.3.0

### ISSUE THREAD

**Issue by sh2sg** [Ji4n1ng/OpenInTerminal#50]
## What is the issue?

Click the toolbar icon, launch iTerm with 2 tabs. one with default folder, one with current Finder folder.

## How does one reproduce the issue?

Not only first time, but every time. 
I don't like the cmd+W workaround.

## Debug information (Logs, OS, Hardware, Version, etc.)

- Mojave 10.14.6
- iTerm 3.3.0

**Comment by sh2sg** [comment]
In iTerm 3.3.0 Pref/Advanced, if "Open a new window at startup" is set to No, then OpeninTerminal will open 1 window 1 tab in current folder, but clicking ITem icon from Dock/Launchpad will then NOT open any window.... 

Is there any way to wait for iTerm open the window, and just change directory in that window?

**Comment by Ji4n1ng** [comment]
Hi @sh2sg , I have tested iTerm 3.3.0 and it works on my machine. Have you set iTerm with the following command?

```
# Open a new Tab
defaults write com.googlecode.iterm2 OpenFileInNewWindows -bool false
# Open a new Window
defaults write com.googlecode.iterm2 OpenFileInNewWindows -bool true
```

This will change the following settings:

<img width="986" alt="Screen Shot 2019-08-06 at 12 30 47 PM" src="https://user-images.githubusercontent.com/11001224/62511407-19b49f80-b846-11e9-8af8-ec0fab0e2245.png">

And the settings of "Open a new window at startup" on my machine are:

<img width="972" alt="Screen Shot 2019-08-06 at 12 30 54 PM" src="https://user-images.githubusercontent.com/11001224/62511416-2802bb80-b846-11e9-8143-5ed03f3b40f2.png">

**Comment by Ji4n1ng** [comment]
The old version of OpenInTerminal opens the iTerm using `cd xxx`. But it will leave useless `cd xxx` in command history. So #36 changed the way of opening iTerm. You could reset the preferences of iTerm to default. And use the command said above to control opening a window or a tab.

**Comment by sh2sg** [comment]
I have exact same settings as yours. But it still opened 2 tabs.

I recorded a screen video to demo this behaviour, please get it from [here](http://www.sh2sg.com/test.mov)

**Comment by sh2sg** [comment]
dunno what happened but it is working now... settings:

open files in new window, not new tab = Yes
open a window at startup = Yes
open a new window when you click the dock icon and no windows are already open, and also on app launch when no other windows are open. = No

I kept changing these settings and finally, it started working...

**Comment by Ji4n1ng** [comment]
I'm glad to know that it works fine.
