### ISSUE TITLE
a more generic editor icon

### ISSUE THREAD

**Issue by pynixwang** [Ji4n1ng/OpenInTerminal#51]
## Summarize this feature

like generic terminal icon.

## Why should this feature be included?

I dont like vscode icon

**Comment by Ji4n1ng** [comment]
The next version will add a generic icon.

**Comment by Ji4n1ng** [comment]
OpenInEditor-Lite v1.0.2 has added a generic icon.

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.0.2
