### ISSUE TITLE
Unable to launch this App 2.0.4

### ISSUE THREAD

**Issue by Xwoder** [Ji4n1ng/OpenInTerminal#53]
## What is the issue?
Unable to launch after upgrade from 2.0.3 to 2.0.4 or reinstall after uninstall it

## How does one reproduce the issue?
Just click the app after installed it.

## Screenshots
None.

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS: 10.14.6 (18G87)
Hardware: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
App Version: 2.0.4

**Comment by gee1k** [comment]
@Ji4n1ng 昨天重装系统了。安装了2.0.3之后，安装 iTerm2 、 VSCode 之后。一直显示未安装
今天说卸载重装一下，结果2.0.4又打不开了。。。

**Comment by Ji4n1ng** [comment]
@Xwoder @gee1k 非常抱歉，我这边没问题，但是在其他人的电脑上确实有这些问题，正在解决。

**Comment by gee1k** [comment]
@Ji4n1ng 卧槽。我的软件也是。别人都打不开了。突然的。没更新版本。。。

**Comment by gee1k** [comment]
@Ji4n1ng 解决了吗？我的软件也是打不开，发现应该是签名问题。确认一下 developer team 之后。重新打包就好了

**Comment by Ji4n1ng** [comment]
@gee1k 确实是签名的问题，坚决不用 Xcode-beta 了，又翻车了。现在运行没问题了，但是你那边还有 iTerm2 和 VSCode 未安装的问题吗？

**Comment by gee1k** [comment]
@Ji4n1ng 有发布新版本吗？还是重新安装一下 2.0.4

**Comment by Ji4n1ng** [comment]
@gee1k 正在解决这个应用未安装的问题，还没发新版本

**Comment by gee1k** [comment]
@Ji4n1ng 可以给个联系方式，给个好友位吗😂

**Comment by gee1k** [comment]
> @gee1k 确实是签名的问题，坚决不用 Xcode-beta 了，又翻车了。现在运行没问题了，但是你那边还有 iTerm2 和 VSCode 未安装的问题吗？

我现在打不开，没法测试这个问题

**Comment by Ji4n1ng** [comment]
@gee1k 可以啊，你给 contact@jianing.wang 发个邮件，我回复你联系方式。

**Comment by Ji4n1ng** [comment]
@Xwoder @gee1k [v2.0.5](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.0.5) 已经解决这个问题了，非常抱歉带来的麻烦。如果有问题，欢迎来提问。brew 还没更新，更新完之后，我会通知你们。

**Comment by Ji4n1ng** [comment]
@Xwoder @gee1k v2.0.5 已经可以通过 brew cask 更新了

**Comment by gee1k** [comment]
@Ji4n1ng 收到，已经安装。两个问题都好了🤙
