### ISSUE TITLE
Single Click on Finder toolbar icon to open selected app 

### ISSUE THREAD

**Issue by hubchau** [Ji4n1ng/OpenInTerminal#54]
## Summarize this feature
I believe that the previous behaviour was "one click on the icon in the Finder toolbar would open the Terminal in the current directory". I'd like this one back

## Why should this feature be included?
It was the default behaviour and required far less clicks

**Comment by Ji4n1ng** [comment]
Sorry, I didn't understand what you mean. If you want to "click once to open Terminal", you can use [OpenInTerminal-Lite](https://github.com/Ji4n1ng/OpenInTerminal/blob/master/Resources/README-Lite.md).

**Comment by hubchau** [comment]
Oh perfect! I didn't catch the difference between the 2 apps. Thanks a lot!
