### ISSUE TITLE
Can't open new tab in Terminal

### ISSUE THREAD

**Issue by alphatr** [Ji4n1ng/OpenInTerminal#55]
## What is the issue?

Can't open new tab in Terminal

## How does one reproduce the issue?

Normal operation, allow finder and terminal permissions, and run `defaults write wang.jianing.OpenInTerminal-Lite OIT_TerminalNewOption tab` in terminal;

## Screenshots

![open](https://user-images.githubusercontent.com/1798972/64335957-7d311900-d00e-11e9-98c1-e01137d303a1.gif)

## Debug information (Logs, OS, Hardware, Version, etc.)

macOS 10.14.6, OpenInTerminal-Lite v1.0.2, Terminal Version 2.9.5 (421.2), shell zsh;

log output

```
default	19:09:08.600101 +0800	OpenInTerminal-Lite	MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported
default	19:09:08.768656 +0800	OpenInTerminal-Lite	UNIX error exception: 17
default	19:09:08.771917 +0800	OpenInTerminal-Lite	UNIX error exception: 17
default	19:09:08.774357 +0800	OpenInTerminal-Lite	UNIX error exception: 17
default	19:09:09.017182 +0800	OpenInTerminal-Lite	skipped scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" because it is not SIP-protected.
default	19:09:09.017232 +0800	OpenInTerminal-Lite	skipped scripting addition "/Library/ScriptingAdditions/SASyphonInjector.osax" because it is not SIP-protected.
default	19:09:09.017273 +0800	OpenInTerminal-Lite	skipped scripting addition "/Library/ScriptingAdditions/BartenderHelper.osax" because it is not SIP-protected.
default	19:09:09.199198 +0800	OpenInTerminal-Lite	skipped scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" because it is not SIP-protected.
default	19:09:09.199260 +0800	OpenInTerminal-Lite	skipped scripting addition "/Library/ScriptingAdditions/SASyphonInjector.osax" because it is not SIP-protected.
default	19:09:09.199304 +0800	OpenInTerminal-Lite	skipped scripting addition "/Library/ScriptingAdditions/BartenderHelper.osax" because it is not SIP-protected.
```

PS: Open in new window is ok.

**Comment by Ji4n1ng** [comment]
3 steps when you first open OpenInTerminal-Lite.

1. click ok

<img width="420" alt="Screen Shot 2019-09-05 at 8 07 09 PM" src="https://user-images.githubusercontent.com/11001224/64340544-02b9c680-d019-11e9-8c3b-65da9c688378.png">

2. Open system preferences

<img width="461" alt="Screen Shot 2019-09-05 at 8 07 15 PM" src="https://user-images.githubusercontent.com/11001224/64340611-2715a300-d019-11e9-9607-b83498a4f591.png">

3. Check OpenInTerminal-Lite.app

<img width="668" alt="Screen Shot 2019-09-05 at 8 09 43 PM" src="https://user-images.githubusercontent.com/11001224/64340627-30067480-d019-11e9-8261-c009b6982a49.png">

If there is no option of OpenInTerminal-Lite, you can use the following command to reset the permissions in the System Preferences and then reopen OpenInTerminal-Lite

```
tccutil reset AppleEvents
```

**Comment by alphatr** [comment]
I just did it like this, still can't open in new tab.

![1](https://user-images.githubusercontent.com/1798972/64396881-bced1480-d091-11e9-9711-f3b6bd1eb4b3.gif)

**Comment by Ji4n1ng** [comment]
Please check these options.

<img width="668" alt="Screen Shot 2019-09-06 at 10 37 10 AM" src="https://user-images.githubusercontent.com/11001224/64397046-616f5680-d092-11e9-89d6-8baf3491ef77.png">

**Comment by alphatr** [comment]
This options don't include `Terminal`

<img width="668" src="https://user-images.githubusercontent.com/1798972/64397809-14d94a80-d095-11e9-823e-d93f61b8262c.png">

**Comment by Ji4n1ng** [comment]
You can try to use the following command to reset the permissions in the System Preferences and then reopen OpenInTerminal-Lite.

```
tccutil reset AppleEvents
```

**Comment by alphatr** [comment]
still as before, can't open in new tab, but this time Automation has Terminal option.

<img width="668" alt="1" src="https://user-images.githubusercontent.com/1798972/64398640-240dc780-d098-11e9-8fc6-974d596a2eb9.png">

**Comment by Ji4n1ng** [comment]
Is there still this problem? It works well on my machine. Currently close this issue.

You can try the new version: 

OpenInTerminal [v2.1.1](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.1.1) and OpenInTerminal-Lite [v1.1.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.1.0)

If it still doesn't work, please let me know!
