### ISSUE TITLE
Icon too small

### ISSUE THREAD

**Issue by molvqingtai** [Ji4n1ng/OpenInTerminal#56]
Icon too small

![image](https://user-images.githubusercontent.com/26295698/64584277-a662f800-d3c6-11e9-9208-66631b588999.png)

OpenInTerminal-Lite: v1.0.2
MacOS: 10.13.6
Resolution: 2560 x 1440

**Comment by Ji4n1ng** [comment]
Hi @molvqingtai . This is indeed a problem. Because I don't have a 10.13.6 device, it's hard to test which size fits. So I suggest you use OpenInTerminal which uses the Finder extension. This should fit nicely into the size of the Finder toolbar icon.
