### ISSUE TITLE
Open iTerm in new split pane

### ISSUE THREAD

**Issue by haakonstorm** [Ji4n1ng/OpenInTerminal#57]
## Summarize this feature
Click button to open iTerm, then create a new split pane.

## Why should this feature be included?
Because a single window with many split panes are better than multiple tabs/windows.

## Additional information
Additionally, if your app could be configurable. iTerm is scriptable. So you can query iTerm and see that the window is 400px wide, and has two split panes. Then when you open a new split pane with your app, you can split a new pane and increase the window size to 600px.

**Comment by Ji4n1ng** [comment]
Hi @haakonstorm Open iTerm with a new split pane. And the current work directory for each panel is the current path. Do you mean this?

**Comment by Ji4n1ng** [comment]
Open a split pane with the current path like the screenshot above. 

<img width="570" alt="2" src="https://user-images.githubusercontent.com/11001224/66294355-62a6d400-e91b-11e9-8c1e-4020a11e4ebd.png">

Or just open a split pane like the following screenshot.

<img width="570" alt="1" src="https://user-images.githubusercontent.com/11001224/66294370-68041e80-e91b-11e9-8321-103be79148d1.png">

**Comment by haakonstorm** [comment]
- Your solution appears to me to be the most advanced of all the apps I've seen that tries to bridge the gap between terminal and file browser.
- What would be awesome would be for your app to become the #1 place developers and users could rely on in order to accomplish this, and also automate other things
- What is needed is really an app that continually could monitor the terminal(s) and file browser(s) in use
  - iTerm is scriptable and can be queried about file path, user and hostname, as well as pane/tab/window configuration
  - Finder can be queried:
  - Marta file browser (awesome!) I'm not sure but developer can add if enough people are intereste I think, it's an awesome project and really nice developer
- Hotkey in Finder to navigate to latest terminal folder (like a "back" button in browser)
- Hotkey in iTerm to navigate to latest Finder folder (like "back" above)

+ (unrelated to this particular issue, but nonetheless)
- solution as to how to make Finder follow when you ssh tunnel to another host; there are sftp solutions for Finder, I've not tested yet, but iTerm knows "where you are" on the host so your solution needs to feed the Finder plugin the directory and they can be synched. Many people would love to have this functionality somehow.

**Comment by Ji4n1ng** [comment]
Sorry, I don't understand what you want. You need a feature which is opening iTerm with a split pane. The following AppleScript can meet this need. I will add this script in OpenInTerminal to support this feature. Of course, users can configure how many panels to open. 

```
tell application "iTerm"	
	open "/Users/YourName/Downloads"		
	select first window		

	# Split pane	
	tell current session of current window		
		split vertically with default profile		
	end tell	
end tell
```

> Hotkey in Finder to navigate to latest terminal folder (like a "back" button in browser)

I don't understand what this means. You can click OpenInTerminal in Finder Toolbar to open the terminal.

> Hotkey in iTerm to navigate to latest Finder folder (like "back" above)

You can input `open .` in iTerm to open the current directory in Finder.

**Comment by haakonstorm** [comment]
1.
- I switch between many File Browsers, I use Marta and Finder most.
- I swith between many Terminals, (Apple Terminal, iTerm2)
- Need something to bind everything together

2.
>>    Hotkey in iTerm to navigate to latest Finder folder (like "back" above)
> You can input open . in iTerm to open the current directory in Finder.

If you are already in Finder, then you need to go back to iTerm, then type (´open -a Finder .`) in my case since Marta is default. 

Better to have a hotkey (say  `⌘⌥i`) that navigates to the LAST directory from your LAST USED iterm window/pane. If you press it again, go "back in history" i.e. the previous last used directory. Or cycle between the directories open in all your open/active tabs.

See?
