### ISSUE TITLE
Set menu text according to the settings

### ISSUE THREAD

**Issue by hiugiak** [Ji4n1ng/OpenInTerminal#58]
## Summarize this feature
Change the menu text according to the settings. For example, if the VS Code is set as the default editor, the corresponding option in menu would display "Open in VS Code" instead of "Open Editor".

## Why should this feature be included?
Obviously, the word "editor" or "terminal" is more general, while "VS Code" or "iTerm" is more specific and is exactly what we think when the menu pops. So I believe replacing "editor" and "terminal" with specific names would make the options in menu easy to find.

**Comment by Ji4n1ng** [comment]
@hiugiak Good suggestion! This feature will be added in next version.

**Comment by Ji4n1ng** [comment]
OpenInTerminal [v2.1.1](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.1.1) and OpenInTerminal-Lite [v1.1.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.1.0) have been released. The new version supports this feature.
