### ISSUE TITLE
Can it be possible not launch at login

### ISSUE THREAD

**Issue by L1cardo** [Ji4n1ng/OpenInTerminal#59]
## Summarize this feature
I found an [app](https://apps.apple.com/cn/app/easy-new-file/id1162194131?mt=12) in APP store ,and it is very similar to OpenInTerminal, and it dosn't need launch at login .
So can it be possible not to launch at login ?
BTW ,OpenInTerminal is an awesome APP !
## Why should this feature be included?
not to launch at login

**Comment by Ji4n1ng** [comment]
OpenInTerminal [v2.1.1](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.1.1) and OpenInTerminal-Lite [v1.1.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.1.0) have been released. The new version supports this feature.

**Comment by L1cardo** [comment]
I ran into a problem that this app did not work

**Comment by Ji4n1ng** [comment]
Could you provide me with more details, like screenshots or alert message?

**Comment by L1cardo** [comment]
![2020-01-09 15-07-56 2020-01-09 15_11_49](https://user-images.githubusercontent.com/33802186/72045967-610df300-32f2-11ea-83b0-8e363a9ddbb1.gif)

**Comment by Ji4n1ng** [comment]
Try to select a file(folder) or open a Finder window. Because you right-click on the desktop and nothing is selected, system does not provide program with the path of selected files. Under this situation, the program does not work. I will put this on FAQ.

**Comment by L1cardo** [comment]
Status bar icon worked fine when I selected the destop. Only the finder extension is not working

**Comment by Ji4n1ng** [comment]
Yes. Currently they do not work as the same way. Finder extension is completely dependent on AppleScript in order to run independently, while status bar icon works as before. So they have different behaviors. This problem will be improved in the future.

**Comment by L1cardo** [comment]
Ok , got it.
