### ISSUE TITLE
quick start not working

### ISSUE THREAD

**Issue by L1cardo** [Ji4n1ng/OpenInTerminal#60]
## What is the issue?
quick start not working
## Screenshots
![image](https://user-images.githubusercontent.com/33802186/66702104-7052c400-ed36-11e9-8a3a-4eb9f55bfa9e.png)

## Debug information (Logs, OS, Hardware, Version, etc.)
OS：macOS 10.15
Hardware：MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
Version：2.0.5

**Comment by Ji4n1ng** [comment]
我在 10.15 测试过这个功能了，功能正常。你可以尝试取消这个功能，然后再次勾选试试。不行的话，可以去 **高级** 里面重置设置，然后重新设置一下。

**Comment by L1cardo** [comment]
你说的两个方法我都试过了，电脑也重新启动了，但是还是不行

**Comment by Ji4n1ng** [comment]
之前是正常可用的吗？是升了系统才这样的吗？快速切换需要左击状态栏启动，右击打开菜单。（触控板双指是右键，单指是左键）

**Comment by L1cardo** [comment]
哦哦 是系统状态栏啊，可以工作的，我理解错了
软件里面显示菜单栏，我以为是finder的上面
或者可以出一个这样的功能吗？  直接点击finder就可以快速启动，不必要再把鼠标拉到屏幕最上方的状态栏

![image](https://user-images.githubusercontent.com/33802186/66800108-92bb2c00-ef46-11e9-9621-e4f5bb4ca89d.png)
![image](https://user-images.githubusercontent.com/33802186/66800115-96e74980-ef46-11e9-8611-6401de6aa3b6.png)

**Comment by Ji4n1ng** [comment]
我描述的有问题，后面版本会更改。如果你想在 Finder 一键启动，请看 https://github.com/Ji4n1ng/OpenInTerminal/blob/master/Resources/README-Lite-zh.md

**Comment by L1cardo** [comment]
> 我描述的有问题，后面版本会更改。如果你想在 Finder 一键启动，请看 https://github.com/Ji4n1ng/OpenInTerminal/blob/master/Resources/README-Lite-zh.md

你的这个我了解过，但是我还是需要OpenInTerminal的功能，另外一个太轻量了，很多功能没有的
希望后续能加个功能，把我说的加进OpenInTerminal里面
