### ISSUE TITLE
Can not open terminal in the correct path

### ISSUE THREAD

**Issue by L1cardo** [Ji4n1ng/OpenInTerminal#62]
## What is the issue?
Can not open terminal in the correct path

## How does one reproduce the issue?
Just open terminal in Desktop, but it opened in Downloads
## Screenshots

![QQ20191024-170525-HD 2019-10-24 17_12_05](https://user-images.githubusercontent.com/33802186/67471115-74a9a600-f681-11e9-991d-a93eee79ca62.gif)

## Debug information (Logs, OS, Hardware, Version, etc.)
os: 10.15
hardware: MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
version: 2.0.5

**Comment by Ji4n1ng** [comment]
@L1cardo OpenInTerminal 的工作顺序是

1. 寻找你有没有选中一个文件或文件夹
2. 寻找最上面的文件夹
3. 如果都没有，则打开桌面

你在右击桌面时，其实并没有选中任何东西，会执行第二步，然后打开了你的桌面。目前，没有合适的 API 可以得到你鼠标右击点的位置所在的目录，所以目前的实现方式还不是很完美。

**Comment by L1cardo** [comment]
@Ji4n1ng App Store 里面有[一款APP](https://apps.apple.com/cn/app/easy-new-file/id1162194131?mt=12)，虽然不是开源的，但是能做到类似的效果，而且他能直接打开桌面。不是开源的，所以不知道他是怎么做到的，希望你在有空的时候能研究一下，麻烦了

**Comment by Ji4n1ng** [comment]
嗯嗯。应该是还有其他的实现办法，我会有空研究一下。

**Comment by L1cardo** [comment]
@Ji4n1ng 麻烦你了，谢谢！！
