### ISSUE TITLE
launch at login not working

### ISSUE THREAD

**Issue by huahuayu** [Ji4n1ng/OpenInTerminal#64]
## What is the issue?
launch at login not working

## How to reproduce?
mac os version: 10.14.5
openInTerminal version: 2.0.1

even though I have checked the launch at login option in preference but when restart mac, openInTerminal is actually not launched, thus in finder when right-click to open current dir in terminal the function is not working, unless open openInTerminal.app by manual from launchpad.

**Comment by Ji4n1ng** [comment]
Is there any other `OpenInTerminal.app` on your computer? For example, the old version of OpenInTerminal which is in `Trash`, or you have tried to compile OpenInTerminal with Xcode. These extra copies can confuse LaunchServices. You should delete them.

Find all copies that LaunchServices knows about:

```
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -dump | grep OpenInTerminal.app
```

Delete the extra copies which path is not started with `/Applications`.

After deleting the extra copies, reset the LaunchServices database: (This will reset all the launch services. Be careful!)

```
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
```

Finally, reopen OpenInTerminal.app and set it to launch at login.

Please let me know if it works.

**Comment by Ji4n1ng** [comment]
Is there still this problem? It works well on my machine. Currently close this issue.

You can try the new version: 

OpenInTerminal [v2.1.1](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.1.1) and OpenInTerminal-Lite [v1.1.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.1.0)

OpenInTerminal v2.1.1 supports Finder Extension Standalone Operation Mode. Finder Extension can run without keeping OpenInTerminal in background. So you don't need to set it to launch at login.
