### ISSUE TITLE
Open two terminal windows after clicking the icon on the toolbar

### ISSUE THREAD

**Issue by Lxnii** [Ji4n1ng/OpenInTerminal#66]
## What is the issue?

If there is no terminal running in the background, when I click the OpenInTerminal-Lite icon on the toolbar, it will automatically open two terminals, one is the terminal of the root directory, and the other is the terminal of the current folder directory. Is there any way to fix it?

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS 10.14.6
OpenInTerminal-Lite 1.0.2
terminal.app

**Comment by Ji4n1ng** [comment]
Please see FAQ in README.

#35
