### ISSUE TITLE
Add custom option to remove right click item

### ISSUE THREAD

**Issue by irexyc** [Ji4n1ng/OpenInTerminal#67]
## Summarize this feature

Add custom option to remove right click item

## Why should this feature be included?

Sometimes the right click memu is too messy and it would slow if the item so many

## Additional information

![](https://i.loli.net/2019/11/19/xAbL65OGyuIqnDp.jpg)

**Comment by Ji4n1ng** [comment]
Good suggestion! This feature will be added in next version.

**Comment by Ji4n1ng** [comment]
OpenInTerminal [v2.1.1](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.1.1) and OpenInTerminal-Lite [v1.1.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.1.0) have been released. The new version supports this feature.
