### ISSUE TITLE
Where are the icons for OpenInEditor-Lite?

### ISSUE THREAD

**Issue by sudo-suhas** [Ji4n1ng/OpenInTerminal#69]
I am unable to find the icons shown in the screenshot for lite icons - https://github.com/Ji4n1ng/OpenInTerminal/blob/master/Resources/README-Lite.md. I was not able to find it in the release. File search on Github did not yield any results either.

Could you please help me locate the dark icon for 'Open in VSCode'?

**Comment by Ji4n1ng** [comment]
Hi. It is in OpenInTerminal-Lite's release. 

OpenInTerminal-Lite release: 
https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.0.2
icons:
https://github.com/Ji4n1ng/OpenInTerminal/releases/download/1.0.2/icons.zip

**Comment by sudo-suhas** [comment]
Thanks! Why don't these icons show up in file search here - https://github.com/Ji4n1ng/OpenInTerminal/find/master ?

**Comment by Ji4n1ng** [comment]
These icons are in the Sketch file. I export them on my Mac and upload them when OpenInTerminal-Lite release. And I will upload them to the repository. 😀

**Comment by sudo-suhas** [comment]
Great :smile:
Thanks for the cool app!
