### ISSUE TITLE
[Feature Request] Add Open in VS Code option

### ISSUE THREAD

**Issue by spencerwooo** [Ji4n1ng/OpenInTerminal#7]
因为现在「用 VS Code 打开」的右键菜单隐藏太深，很不方便，希望可以添加一个用 VS Code 打开的选项。

**Comment by Ji4n1ng** [comment]
其实这个想法新版本已经在做了。只是形式还在探索。目前采用的形式是，Finder Toolbar 的弹出菜单中。但是这就需要点击两下，第一下点出菜单，第二下选择终端（或者选择打开vscode）。我不知道大多数的用户，是否很在意这多出来的一下点击所带来的使用成本。我想听听你的意见。

**Comment by Camji55** [comment]
In the case that 2 clicks is deemed acceptable, it certainly wouldn't be a difficult thing to add. Potentially a Settings screen where you can select which apps you want to open with?

The only problem with this is that is not related to what the project was made for. The project is "OpenInTerminal" so being able to open in something other than a Terminal seems kind of off.

**Comment by spencerwooo** [comment]
@Ji4n1ng 其实我觉得弹出一个下拉菜单也是可以接受的。目前我自己的解决方案是用 Automator 另外写了一个打开 VS Code 的 Workflow，然后将它转换为 `.app` 的应用程序格式来把它放在 Finder 的工具栏上：

<img width="253" alt="Open in VS Code" src="https://user-images.githubusercontent.com/32114380/56402769-3c1fae80-6291-11e9-8a46-569d5ef2a4e5.png">

我没有解决的问题是「我打开一个 Finder 目录之后，不选择文件，就直接用 VS Code 打开当前路径」，也就是说我需要单击选择一个文件夹才能把其路径传给 Automator。我觉得 OpenInTerminal 应该很好解决这个问题吧~

@Camji55 I understand. But I think OpenInTerminal is fully capable of more than just "opening current working directory in a terminal", and it would be awesome if we can use OpenInTerminal for custom applications, in this case: VS Code. macOS (Well, I think) lacks a ready-to-use right-click context menu, and customizing a workflow with automator just isn't that convenient.

**Comment by Ji4n1ng** [comment]
@spencerwooo 你所说的这个问题，OpenInTerminal 会解决的，实现打开 VSCode 应该不难。但是正如 Camji55 所说，这是 OpenInTerminal，不是 OpenInAnything，加上过多的功能会让一些用户感到困惑。但是你所说的功能，是在接下来的考虑之内的。你可以期待新的版本或者说是一个新的应用。非常感谢你的建议。😃

**Comment by Camji55** [comment]
@Ji4n1ng @spencerwooo I am closing this ticket. It can be tracked in https://github.com/Ji4n1ng/OpenInTerminal/issues/22 from now on.

**Comment by Ji4n1ng** [comment]
@spencerwooo v0.9.0 已经发行了。这个版本支持一键打开到 VSCode 等编辑器。你可以下载试一试，更多说明请看 ReadMe

**Comment by spencerwooo** [comment]
@Ji4n1ng NB，感谢~♥

**Comment by Ji4n1ng** [comment]
@spencerwooo 不客气 😀
