### ISSUE TITLE
Open multiple selected files?

### ISSUE THREAD

**Issue by luckman212** [Ji4n1ng/OpenInTerminal#71]
**v1.0.2** (macOS 10.15.2)

Does OpenInEditor-Lite support multiple selected files? I tried it (editor set to SublimeText) and it only opens 1 file. This would be a nice thing to support... not sure if it's possible?

**Comment by Ji4n1ng** [comment]
Hi, luckman212. Currently, OpenInEditor-Lite only open one of the files you selected in your editor. And it's possible to support multiple files. But when you select both files and folders, it's hard to say if your editor supports this feature. I have tested this on VSCode and BBEdit and it works.
 
This feature will be added in the next version. Thanks for your suggestion!

**Comment by luckman212** [comment]
Sounds good. Not sure about opening a mix of files/folders in Sublime Text, but highlighting a single folder and clicking OpenInEditor-Lite works (opens as a project in Sidebar)

**Comment by luckman212** [comment]
Hi @Ji4n1ng, is this feature still planned?

**Comment by Ji4n1ng** [comment]
Hi @luckman212 , I am very sorry that this function has not been implemented yet. And my answer is that this feature is still planned. But since I'm on the deadline for the paper recently, it may take one or two months before I have time to work on this feature. Thank you for your support to OpenInTerminal!

**Comment by Ji4n1ng** [comment]
@luckman212 OpenInTerminal 2.2.3 and OpenInEditor-Lite 1.1.4 support this feature. BTW, this only works when you open files or folders in editors not terminals. Please let me know if you have any questions!😀

**Comment by luckman212** [comment]
@Ji4n1ng Wow this is great, thank you for implementing this! I just installed & tested — works great! 🚀
