### ISSUE TITLE
Finder other Disk icon modified in 10.15.2

### ISSUE THREAD

**Issue by AppOJBK** [Ji4n1ng/OpenInTerminal#72]
## What is the issue?
Finder Disk icon modified

## Screenshots
<img width="788" alt="iShot     2019-12-28 16 37 59" src="https://user-images.githubusercontent.com/34768417/71541226-94ff2500-2990-11ea-8719-3d0546c96373.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS 10.15.2
OpenInTerminal 2.0.5

**Comment by Ji4n1ng** [comment]
I'm not sure this issue is related to OpenInTerminal. Could you provide me with more details?

**Comment by Ji4n1ng** [comment]
This issue was closed because the given information was not enough.
