### ISSUE TITLE
Catalina said OpenInTerminal-Lite is a malware

### ISSUE THREAD

**Issue by sh2sg** [Ji4n1ng/OpenInTerminal#73]
## What is the issue?
Unable to launch it, even after reinstalled.

It has been working fine for months, and stopped working today.

## How does one reproduce the issue?
- downloaded OpenInTerminal-Lite v1.0.2
- extracted it to Applications
- cmd drag to Finder toolbar
- clicked the icon, macOS refused to open it, said it is a malware.

## Screenshots
<img width="448" alt="iShot     2019-12-30 23 34 08" src="https://user-images.githubusercontent.com/3245152/71588844-f0cad900-2b5d-11ea-8dbc-bd81a1192e3c.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS Catalina 10.15.2

**Comment by gingerbeardman** [comment]
App has stopped launching on Mojave also.

**Comment by gingerbeardman** [comment]
![Screen shot 2019-12-30 at 16 15 24](https://user-images.githubusercontent.com/49612/71590240-9c086d80-2b1f-11ea-9ef0-ae2e3f3be44d.png)

**Comment by Ji4n1ng** [comment]
Sorry guys. I will re-sign the new version of OpenInTerminal-Lite as soon as possible.

**Comment by Ji4n1ng** [comment]
Hello @sh2sg @gingerbeardman . OpenInTerminal-Lite(OpenInEditor-Lite) v1.0.3 has released. 

Because I signed the application with the developer account, Bundle ID has changed. Please check the document if you want to change default settings.

https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.0.3

**Comment by Ji4n1ng** [comment]
> So...
> 
> ![Screen shot 2019-12-30 at 16 15 24](https://user-images.githubusercontent.com/49612/71590240-9c086d80-2b1f-11ea-9ef0-ae2e3f3be44d.png)
> 
> Workaround is to build from source or resign the app, whichever you are more comfortable doing.

@gingerbeardman By the way, please tell me how you got this screenshot. Thank you very much!

**Comment by hotel-dieu** [comment]
I am not the original poster, but I am positive that the screenshot comes from the [WhatsYourSign utility](https://objective-see.com/products/whatsyoursign.html) by Objective-See.

**Comment by Ji4n1ng** [comment]
That's it! Thanks a lot! @hotel-dieu

**Comment by Ji4n1ng** [comment]
Now OpenInTerminal-Lite and OpenInEditor-Lite can be updated via Homebrew cask.
