### ISSUE TITLE
在显示桌面的情况下不能正确的打开或复制路径

### ISSUE THREAD

**Issue by firstmetcs** [Ji4n1ng/OpenInTerminal#74]
如果我在Mac下使用四指张开或者按F11来显示桌面的情况下，在桌面右键点击复制路径、打开终端的任意一个都会默认打开访达最近一次访问的路径，而不是桌面的路径。我觉得这可能是个bug

**Comment by Ji4n1ng** [comment]
我知道这个事情，这个目前没有解决办法。你在桌面空白位置右键的时候，不算是选中了一个文件或者一个文件夹，系统的API没有给我返回对应的路径。所以只能从你之前选中的文件或者最上面的访达窗口来打开终端。

**Comment by firstmetcs** [comment]
这个问题的话我有个插件是新建文件的，在桌面右键新建文件可以识别到正确的路径

**Comment by firstmetcs** [comment]
> 我知道这个事情，这个目前没有解决办法。你在桌面空白位置右键的时候，不算是选中了一个文件或者一个文件夹，系统的API没有给我返回对应的路径。所以只能从你之前选中的文件或者最上面的访达窗口来打开终端。

这个问题的话我有个插件是新建文件的，在桌面右键新建文件可以识别到正确的路径

**Comment by Ji4n1ng** [comment]
我知道有的应用可以做到，目前还不清楚他是怎么实现的。后续再改进吧。

**Comment by firstmetcs** [comment]
> 我知道有的应用可以做到，目前还不清楚他是怎么实现的。后续再改进吧。

OK，感谢

**Comment by moriwang** [comment]
> 我知道这个事情，这个目前没有解决办法。你在桌面空白位置右键的时候，不算是选中了一个文件或者一个文件夹，系统的API没有给我返回对应的路径。所以只能从你之前选中的文件或者最上面的访达窗口来打开终端。

我也遇到了这个问题，现在在桌面空白的状态下，拷贝路径是可以用的，但是在终端或者编辑器打开无法使用。那按照上面的逻辑，如果可以取得路径，后续操作应该会有继续的可能性。或者另一种比较暴力的方式不知道有没有缺陷，如果系统 API 没有返回路径，就判定为他在空白桌面，返回 finder 中桌面文件夹的路径。

OpenInTerminal: 2.1.1
OS: macOS 10.15.4

**Comment by Ji4n1ng** [comment]
@moriwang 这个问题已经解决了，在桌面空白的状态下，可以打开终端或者编辑器。新版本可能要过段时间发出来，还有个功能没做完。
