### ISSUE TITLE
10.15.2误报

### ISSUE THREAD

**Issue by dwSun** [Ji4n1ng/OpenInTerminal#76]
更新10.15.2之后，系统提示OpenInEditor-Lite和OpenInTerminal-Lite是有害软件：
<img width="840" alt="WeChated509a749c33255b2ebea5ee0391d6fe" src="https://user-images.githubusercontent.com/5899962/71703423-5c879d00-2e0f-11ea-8e3e-992ee6a2469d.png">

**Comment by Ji4n1ng** [comment]
请更新最新版本软件 1.0.3
