### ISSUE TITLE
Support CotEditor as an editor

### ISSUE THREAD

**Issue by wao1201** [Ji4n1ng/OpenInTerminal#77]
## Summarize this feature
Add the support of **[CotEditor](https://coteditor.com/)** as an editor

## Why should this feature be included?
**CotEditor** is still the best alternative I could find which compares to the Notepad++ on Windows platform.

## Additional information
https://coteditor.com/

**Comment by Ji4n1ng** [comment]
OpenInTerminal [v2.1.1](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.1.1) and OpenInTerminal-Lite [v1.1.0](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/1.1.0) have been released. The new version supports this feature.
