### ISSUE TITLE
mac popup: openInTerminal will damage your compute, you should move it to the trash

### ISSUE THREAD

**Issue by huahuayu** [Ji4n1ng/OpenInTerminal#78]
## What is the issue?
when restart mac a popup comes out
![image](https://user-images.githubusercontent.com/1725060/72067477-cc20ef00-331d-11ea-8c18-98ac6857d74f.png)

## Env
mac os 10.15.2
openInTerminal version: unknown, because I have followed the instruction to remove it from mac

## Question
so what's the problem? apple mistake or openInTerminal app's problem?

**Comment by Ji4n1ng** [comment]
Please update the latest version.
