### ISSUE TITLE
App does not show as finder extension

### ISSUE THREAD

**Issue by rjalexa** [Ji4n1ng/OpenInTerminal#80]
## What is the issue?
The app does not appear in the finder window menubar nor in Extensions->Finder Extensions

The app runs fine when launched

## Debug information (Logs, OS, Hardware, Version, etc.)
Catalina
Installed with brew cask install openinterminal-lite command

![image](https://user-images.githubusercontent.com/15216911/73938242-28f4d280-48e7-11ea-8bf7-6640b908176a.png)

![image](https://user-images.githubusercontent.com/15216911/73938144-f64ada00-48e6-11ea-9c80-1e75b90b53c5.png)

**Comment by Ji4n1ng** [comment]
OpenInTerminal and OpenInTerminal-Lite are two different applications. Please see README and FAQ.
