### ISSUE TITLE
OpenInTerminal-Lite and OpenInEditor-Lite don't show up in Finder nor in Extensions

### ISSUE THREAD

**Issue by dserodio** [Ji4n1ng/OpenInTerminal#87]
## What is the issue?

I installed both OpenInEditor-Lite and OpenInTerminal-Lite using Homebrew, but they don't show up in the Finder toolbar nor in the Finder Extensions. I tried to `killall Finder` but it didn't solve the problem.

I read the README, the FAQ, and #80 but I still don't understand what's wrong.

Thank you.

## How does one reproduce the issue?

1. `$ brew cask install openineditor-lite openinterminal-lite`
2. Open Finder
3. Open System Preferences → Extensions → Finder Extensions

## Screenshots

<img width="780" alt="Screen Shot 2020-04-07 at 10 20 33 AM" src="https://user-images.githubusercontent.com/233589/78674449-03218500-78ba-11ea-8c38-d7a6ea8deb2d.png">

<img width="1032" alt="Screen Shot 2020-04-07 at 10 25 26 AM" src="https://user-images.githubusercontent.com/233589/78674590-36fcaa80-78ba-11ea-8c59-841cec85e72b.png">

## Debug information (Logs, OS, Hardware, Version, etc.)

MacBook Pro (13-inch, 2017), macOS 10.14.6

**Comment by Ji4n1ng** [comment]
OpenInTerminal-Lite doesn't have Finder extension.

https://github.com/Ji4n1ng/OpenInTerminal/blob/master/Resources/README-Lite.md#how-to-install-

**Comment by hitzhangjie** [comment]
Hi, I come across the same problem.

OpenInTerminal-Lite v1.1.1
macOS 10.15.3
