### ISSUE TITLE
Finder other Disk icon modified in 10.15.4

### ISSUE THREAD

**Issue by AppOJBK** [Ji4n1ng/OpenInTerminal#88]
## What is the issue?
Finder Disk icon look like OpenInTerminal icon

## Screenshots
<img width="806" alt="iShot2020-04-08上午12 23 44" src="https://user-images.githubusercontent.com/34768417/78694590-7b765d80-792f-11ea-80ec-8fe755aa1306.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
macOS：10.15.4
OpenInTerminal：2.2.0

**Comment by AppOJBK** [comment]
When I install OpenInTerminal：2.1.1

<img width="806" alt="iShot2020-04-08上午12 29 46" src="https://user-images.githubusercontent.com/34768417/78694993-1111ed00-7930-11ea-832e-a58dab5b1a0b.png">

**Comment by AppOJBK** [comment]
I think it's the finder cache bug

**Comment by Ji4n1ng** [comment]
Yes, I think it's a bug of macOS 10.15 too. This feature(OpenInTerminal context menu can show in external disk) was developed in macOS 10.14. There was no such problem at the time, and this piece of code was never changed since then.

same issue #72
