### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by Camji55** [Ji4n1ng/OpenInTerminal#9]
May I make a suggestion in setting up some sort of CI for this project. Possibly with Travis CI?

**Comment by Ji4n1ng** [comment]
Great advice! It’s very embarrassing that I haven’t used CI yet. But I will add CI as soon as possible. Thank you for your kind advice. 😃

**Comment by Ji4n1ng** [comment]
😂

![1](https://user-images.githubusercontent.com/11001224/56405101-3b8d1500-629d-11e9-8dff-ef6b3e50439d.jpg)

**Comment by Camji55** [comment]
> Great advice! It’s very embarrassing that I haven’t used CI yet. But I will add CI as soon as possible. Thank you for your kind advice. 😃

😂Hey, no worries at all. If you need help getting it setup my email is on my profile page. I'd be glad to help!

**Comment by Ji4n1ng** [comment]
OK. Thank you 😃

**Comment by Ji4n1ng** [comment]
Hi @Camji55 ,  I have seen some new issues. It’s like some people like A but others like B. So I added `OpenInTerminal-Lite` as the application currently available to users. This is the continuation of v0.2.0, which is a simple and easy to use version. 

For those who want to use a powerful version, we will continue to develop new features like FinderSync, the settings panel and so on in `OpenInTerminal`.  When `OpenInTerminal` are more mature and stable, we could provide it to the user.

Looking forward for your reply, thank you.

**Comment by Camji55** [comment]
Sounds like a plan!

**Comment by Ji4n1ng** [comment]
If you have any questions about `.travis.yml`, please feel free to change it.

**Comment by Camji55** [comment]
Looks good enough for now! Nice work 👍🏻
