### ISSUE TITLE
Doesn't play nicely with the Dropbox sync icons in Finder

### ISSUE THREAD

**Issue by chrisnoden** [Ji4n1ng/OpenInTerminal#93]
## What is the issue?
The Mac Dropbox app has a Finder extension which displays handy sync status icons. These inform you if the directory/file is synced locally or exists in the cloud only.

When the Open In Terminal finder extension is enabled, it prevents the Dropbox sync icons from appearing.

## How does one reproduce the issue?
- Install one of the recent versions of Dropbox with a Dropbox Professional account. You do not get their SmartSync functionality unless your are on the free trial or have a paid Professional account.
- Enable the Dropbox Finder extension - you will see the icons to the right of the Name when browsing your Dropbox files.
- Enable the Open In Terminal Finder extension and all the smartsync icons will disappear.
- Disable the Open in Terminal Finder extension and the smartsync icons will reappear.

> NB - you may have to restart Finder with a `killall Finder` when enabling/disabling the extensions

## Screenshots
![Screenshot 2020-05-10 at 11 40 13](https://user-images.githubusercontent.com/2600554/81496922-0b9f1e00-92b3-11ea-96a3-fbdd4a3a8be4.png)

## Debug information (Logs, OS, Hardware, Version, etc.)
- MacOS 10.15.4
- Dropbox v96.4.172
- OpenInTerminal 2.2.0

**Comment by Ji4n1ng** [comment]
Sorry for the late reply. This is indeed a problem. And it might still take a long time to fix it. You could use OpenInTerminal-Lite and OpenInEditor-Lite instead.

**Comment by Ji4n1ng** [comment]
Same problem on OneDrive Finder Extension #116 

Same problem on Google Drive Finder Extension #129

**Comment by Ji4n1ng** [comment]
It seems like Apple has fixed this bug. I just noticed that there is no such bug in Big Sur 11.5.2. I haven't used Mac as my main machine for more than half a year, so I don't know which version fixs this. Anyway, glad to see that.

**Comment by stosumarte** [comment]
Hello @Ji4n1ng , sorry for reopening this issue, but the problem persists for me.
I have the latest version of the Dropbox client, OpenInTerminal too and I'm working on macOS 12.7.3.
The steps to reproduce it are identical as described in the first message of this thread.
