### ISSUE TITLE
Cannot detect some Jetbrains apps installed by Jetbrains-Toolbox

### ISSUE THREAD

**Issue by RemiliaDevil** [Ji4n1ng/OpenInTerminal#95]
## What is the issue?
I installed some applications developed by Jetbrains Inc, like Clion.app and Pycharm-professional.app.  However, OpenInTerminal only detects Clion.app as an installed application.
All the Jetbrains series apps are installed by Jetbrains Toolbox using a legal certificate.

## Debug information
OS: Catalina 10.15.4
pycharm version: 2020.1.1

**Comment by Ji4n1ng** [comment]
Hi @RemiliaDevil. Do all unrecognized Jetbrains apps have a '-professional' suffix?

**Comment by RemiliaDevil** [comment]
> Hi @RemiliaDevil. Do all unrecognized Jetbrains apps have a '-professional' suffix?

Not exactly. I found that all unrecognized Jetbrains apps have white space(s) in their names.

Recognized apps:
Clion
Goland
Webstorm

Unrecognized apps:
IntellilJ Idea Ultimate
Pycharm Professional

**Comment by Ji4n1ng** [comment]
Hi @RemiliaDevil OpenInTerminal v2.3.0 and OpenInEditor v1.2.0 support custom app. You may want to try them
