### ISSUE TITLE
Can not detect Terminal on macOS 10.16

### ISSUE THREAD

**Issue by L1cardo** [Ji4n1ng/OpenInTerminal#97]
## What is the issue?
Can not detect Terminal on macOS 10.16
## Screenshots
![image](https://user-images.githubusercontent.com/33802186/85352764-4abec100-b539-11ea-957e-7837e4a98add.png)

## Debug information (Logs, OS, Hardware, Version, etc.)
![image](https://user-images.githubusercontent.com/33802186/85352718-2fec4c80-b539-11ea-99b8-6fe69db8796a.png)

**Comment by deko96** [comment]
+1
![image](https://user-images.githubusercontent.com/11915426/85472243-de33d880-b5b1-11ea-917c-16893d88c752.png)
![image](https://user-images.githubusercontent.com/11915426/85472305-f6a3f300-b5b1-11ea-8598-28d3876b6178.png)

**Comment by Ji4n1ng** [comment]
Oops! I forgot to display the default terminal and editor. This bug will be fixed in the next version.

**Comment by surrutiaquir** [comment]
When will the next version be released? I'm having the same problem, thanks!

**Comment by Ji4n1ng** [comment]
@surrutiaquir The new version will be released this weekend.

**Comment by Ji4n1ng** [comment]
Sorry for being late. This bug was fixed and the new version is [v2.2.2](https://github.com/Ji4n1ng/OpenInTerminal/releases/tag/2.2.2).
