### ISSUE TITLE
macOS 11 finder icon size problem

### ISSUE THREAD

**Issue by viewv** [Ji4n1ng/OpenInTerminal#98]
## What is the issue?
macOS 11 beta, the icon in the finder toolbar is too big, and the menu also have display issue.
But I can still use core function without any problem. 
It seems this problem is caused by macOS new finder UI design.
## How does one reproduce the issue?
Place openInTerminal tool into the finder toolbar.
## Screenshots
<img width="1247" alt="Screen Shot 2020-06-29 at 08 17 15" src="https://user-images.githubusercontent.com/32566594/85962017-f310d180-b9e0-11ea-89a0-a7c1c31450fb.png">

## Debug information (Logs, OS, Hardware, Version, etc.)
OS: macOS 11 beta 1
<img width="698" alt="Screen Shot 2020-06-29 at 08 20 49" src="https://user-images.githubusercontent.com/32566594/85962131-9b269a80-b9e1-11ea-907a-5366a7ccc2ae.png">

**Comment by singularitti** [comment]
This is solved automatically in the latest macOS Big Sur 11.0.1 (20B29).
