### ISSUE TITLE
Cannot be used in Finder

### ISSUE THREAD

**Issue by liuzhihang** [Ji4n1ng/OpenInTerminal#99]
## What is the issue?

Cannot be used in Finder

## How does one reproduce the issue?

![image](https://user-images.githubusercontent.com/26057042/85968208-0af35000-b9f7-11ea-89b8-bbf6ab1d77b7.png)
![屏幕录制2020-06-29 10 56 16 2020-06-29 10_57_27](https://user-images.githubusercontent.com/26057042/85968402-9ec51c00-b9f7-11ea-9a09-b2bcdd793814.gif)

I won't be able to use it even if I restart Finder. But the menu bar can be used.

重启访达也不行，菜单栏的倒是可以使用。

**Comment by liuzhihangs** [comment]
macOS version: 10.15.5 (19F101)

**Comment by oXnMe** [comment]
一样的问题，10.14.6，而且点了会卡好久

**Comment by liuzhihangs** [comment]
macOS version: 10.15.6 (19G73)

**Comment by gulymaestro** [comment]
Same problem...
MacOS 10.15.6 (19G73) in spanish

**Comment by Ji4n1ng** [comment]
OpenInTerminal works fine on my mac(macOS 10.15.6) and I use it every day.
I'm wondering, this problem occurred during the first installation, or the app was used normally before, and suddenly this problem occurred.

**Comment by liuzhihangs** [comment]
> OpenInTerminal works fine on my mac(macOS 10.15.6) and I use it every day.
> I'm wondering, this problem occurred during the first installation, or the app was used normally before, and suddenly this problem occurred.

It has been unavailable since the first installation, but it can be used in the taskbar.

It's just not available in finder, except copy path.

Use Homebrew to install, even if I uninstall and reinstall, it still cannot.

**Comment by Ji4n1ng** [comment]
@liuzhihangs Is there any scripts under the directory `~/Library/Application Scripts/wang.jianing.app.OpenInTerminal.OpenInTerminalFinderExtension`?

<img width="1246" alt="Screen Shot 2020-07-23 at 3 58 30 PM" src="https://user-images.githubusercontent.com/11001224/88264005-9661b780-ccfd-11ea-9889-2200b7d07a1c.png">

**Comment by liuzhihangs** [comment]
@Ji4n1ng 

![image](https://user-images.githubusercontent.com/26057042/88264317-24d63900-ccfe-11ea-8d93-6a74a977a21e.png)

**Comment by Ji4n1ng** [comment]
Please check the options below.

<img width="668" alt="Screen Shot 2020-07-23 at 4 10 30 PM" src="https://user-images.githubusercontent.com/11001224/88264870-1a686f00-ccff-11ea-85dc-2c025bd2959a.png">

**Comment by Ji4n1ng** [comment]
If there is no such option, follow these steps:
1. Run `tccutil reset AppleEvents wang.jianing.app.OpenInTerminal` in Terminal
2. Reopen OpenInTerminal. 
3. Give OpenInTerminal the permissions.

**Comment by liuzhihangs** [comment]
@Ji4n1ng J

![image](https://user-images.githubusercontent.com/26057042/88273209-6a99fe00-cd0c-11ea-8071-0889828bb7c0.png)


还是不能用，也执行命令重新设置了。

**Comment by liuzhihangs** [comment]
@Ji4n1ng j 在任务栏的可以使用，但是 访达中的不可以使用。

**Comment by gulymaestro** [comment]
> If there is no such option, follow these steps:
> 
>     1. Run `tccutil reset AppleEvents wang.jianing.app.OpenInTerminal` in Terminal
> 
>     2. Reopen OpenInTerminal.
> 
>     3. Give OpenInTerminal the permissions.

Work for me... Thx

**Comment by Relieved-hai** [comment]
**Switch MAC system language to English。**
I found it by accident。

**Comment by Relieved-hai** [comment]
> ## What is the issue?
> Cannot be used in Finder
> 
> ## How does one reproduce the issue?
> ![image](https://user-images.githubusercontent.com/26057042/85968208-0af35000-b9f7-11ea-89b8-bbf6ab1d77b7.png)
> ![屏幕录制2020-06-29 10 56 16 2020-06-29 10_57_27](https://user-images.githubusercontent.com/26057042/85968402-9ec51c00-b9f7-11ea-9a09-b2bcdd793814.gif)
> 
> I won't be able to use it even if I restart Finder. But the menu bar can be used.
> 
> 重启访达也不行，菜单栏的倒是可以使用。
> 
> ## Debug information (Logs, OS, Hardware, Version, etc.)

**Switch MAC system language to English。** 将 Mac 的系统语言切换成英文。

**Comment by hsingll** [comment]
一样的问题，在finder的右键菜单和菜单栏菜单中使用打开Vscode和打开Iterm时会卡死，然后没有任何反应。
重置权限再打开允许权限后也一样。

**Comment by shiyicode** [comment]
我也遇到了这个问题，重置权限也没效果。菜单栏可以使用，finder没反应

**Comment by baker221** [comment]
同样遇到了这个问题，重启权限后软件也不会重新申请权限

**Comment by Ji4n1ng** [comment]
非常抱歉各位。非英文版本的 OpenInTerminal 都存在这个问题。这个问题是由于我硬编码了"Open in"的长度。这个问题在新版本 v2.3.0 已经解决了。非常抱歉带来的麻烦。顺便，新版本支持自定义应用，欢迎使用。😀

Sorry everyone. This problem exists in all non-English versions of OpenInTerminal. This problem is because I hardcoded the length of "Open in". This problem has been resolved in the new version v2.3.0. Sorry for the trouble. By the way, the new version supports custom applications, welcome to use. 😀
